### ISSUE TITLE
WebWorker in three-mesh-bvh fails when using bundler

### ISSUE THREAD

**Issue by ajayns** [gkjohnson/three-gpu-pathtracer#107]
**Describe the bug**

When using the package as per example in the repo, it crashes cause WebWorker isn't generated/compiled correctly.

**To Reproduce**

1. Use any bundle like vite, parcel
2. Import one of the examples, I've used the `interior.js` from examples to illustrate.
3. Run on browser, notice error

```
Uncaught TypeError: Failed to construct 'URL': Invalid URL
```

***Code***

[CodeSandbox](https://codesandbox.io/s/inspiring-wave-w3wsnj?file=/src/index.js)

***Live example***

[CodeSandbox](https://codesandbox.io/s/inspiring-wave-w3wsnj?file=/src/index.js)

**Expected behavior**

I know web workers don't play well with bundlers when imported from a node module, but perhaps probably some solution can be found and noted in the README.md?

I've tried using an inline webworker - but that solution isn't best suited as well cause we have some three.js imports in the worker and it only works for js code can be made into a blob directly.

**Screenshots and Repro Model**
Not much to show here it crashes on load

**Platform:**

 - Device: MacBook Pro (16-inch, 2021)
 - OS: MacOS 12.3.1
 - GPU: Apple M1 Max
 - Browser: Chrome
 - Three.js version: 0.139.2
 - Library version: v0.0.1

**Comment by gkjohnson** [comment]
Thanks for the report -- I'm thinking about taking the same approach as three-mesh-bvh and separating out the components that require webworkers into separate exports the user has to import them on their own if it doesn't work with their bundle system.

Ie `PathTracingSceneGenerator` would just be a synchronous implementation:

```js
import { PathTracingSceneGenerator } from 'three-gpu-pathtracer';

const generator = new PathTracingSceneGenerator();
const result = generator.generate( scene );
// ...
```

And a new `AsyncPathTracingSceneGenerator` class (the class names could use some work...) would be added and imported like so (or copied and modified to a projects needs):

```js
import { AsyncPathTracingSceneGenerator } from 'three-gpu-pathtracer/src/workers/AsyncPathTracingSceneGenerator.js';

const generator = new AsyncPathTracingSceneGenerator();
const result = await generator.generate( scene );
// ...
```

What do you think @ajayns? Any thoughts on better class names would be helpful, as well 😁

**Comment by gkjohnson** [comment]
@ajayns just added "PathTracingSceneWorker" which will be available in the next release to separate out the worker requirements. Also updated the docs -- let me know how it looks.
