### ISSUE TITLE
Support for spotlights

### ISSUE THREAD

**Issue by DanielDoesDesign** [gkjohnson/three-gpu-pathtracer#113]
I tried to implement an example of light shining through a transmissive surface only to find the raycaster does not recognize light sources. 

https://i.imgur.com/VnmmqaV.png

https://i.imgur.com/Dz23nMY.jpeg

The effect I am trying to replicate is that similar of the "material ball" example. With a small radial point being emissive with a wide 120 degree angle.

**Comment by Ben-Mack** [comment]
Yes, +1 for basic lights support like SpotLight and DirectionalLight

**Comment by gkjohnson** [comment]
Area lights and volume lights will probably come long before some of these other more fake lights.

**Comment by gkjohnson** [comment]
Sounds like @richardassar is looking into spot light support

**Comment by richardassar** [comment]
Working on adding basic support just now and as a stretch goal I might look into allowing the user to apply a preset texture like this:

![Spot light presets](https://i0.wp.com/odederell3d.blog/wp-content/uploads/2018/09/cgl_spotlight_presets_pack_1-0_previews.jpg?resize=648%2C534&ssl=1)

**Comment by richardassar** [comment]
Sneak peek at the spot lights feature WIP.

![Screenshot 2022-06-13 at 00-06-03 Material Orb Path Tracing](https://user-images.githubusercontent.com/868396/173257271-1ece8895-2613-4df3-968a-0a438895d053.png)

Builds on top of the area lights work by introducing a light type field to the light struct and a PDF tailored to spot lights, all that remains is to add support for all of the THREE.js spot light parameters such as penumbra and decay.

**Comment by bhouston** [comment]
[richardassar](https://github.com/richardassar) Here is the IES light parser we used in Clara.io: https://gist.github.com/bhouston/f2d1935aeabe2630d20c10390ce17cb5

What we did is just create a texture out of it and then use that to modulate the light intensity out of the light.

I think that IES support could be a separate issue and PR with a separate bounty of $250 USD.  I think it is important to keep things bit size.

**Comment by bhouston** [comment]
@richardassar Here is the IES light parser we used in Clara.io: https://gist.github.com/bhouston/f2d1935aeabe2630d20c10390ce17cb5

What we did is just create a texture out of it and then use that to modulate the light intensity out of the light.

I think that IES support could be a separate issue and PR with a separate bounty of $250 USD. I think it is important to keep things bit size.

**Comment by bhouston** [comment]
I've created a separate issue for IES profile support for spot lights here: https://github.com/gkjohnson/three-gpu-pathtracer/issues/181

**Comment by richardassar** [comment]
Posted some progress screenshots [here](https://github.com/gkjohnson/three-gpu-pathtracer/issues/181#issuecomment-1154840714 ) showing the IES profile support.
