### ISSUE TITLE
envMapInfo of PhysicalPathTracingMaterial missing

### ISSUE THREAD

**Issue by samevision** [gkjohnson/three-gpu-pathtracer#153]
Hello Garrett,

First of all, I want to thank you for an effort to work so dedicatedly on the Path Tracer. I am really grateful that you make something like this possible.

Currently I am making my first attempts to integrate the Path Tracer into a project, but I have a few problems. I am working in a NextJs environment and using three@0.139.2 and three-gpu-pathtracer@github:gkjohnson/three-gpu-pathtracer.

I would be very grateful if you could give me a hint what the problem is here.

ptRenderer.material.envMapInfo is undefined but it should return EquirectHdrInfoUniform. Therefore I am not able to set the environment map.

```
const renderer = new WebGLRenderer({ antialias: true })
const ptRenderer = new PathTracingRenderer(renderer)
ptRenderer.material = new PhysicalPathTracingMaterial()
console.log(ptRenderer.material.envMapInfo)
```

I noticed that many values are undefined as well:

- ptRenderer.alpha
- ptRenderer._primaryTarget
- ptRenderer._blendTargets
- ...

The values are correctly specified when I import the PathTracingRenderer from the cloned Github repository. As soon as I use 'three-gpu-pathtracer/src/core/PathTracingRenderer' they are undefined.

Thank you!

Best

**Comment by gkjohnson** [comment]
Hi @samevision! The environment map importance sampling has not been published in a release yet. Take a look at the v0.0.2 docs for the latest npm version usage: https://github.com/gkjohnson/three-gpu-pathtracer/tree/v0.0.2

v0.0.3 with environment map importance sampling will be released some time next week.

**Comment by samevision** [comment]
Thank you for the feedback! It works now. I am really looking forward to v0.0.3!
