### ISSUE TITLE
Some Materials cause exceptions and break the renderer entirely

### ISSUE THREAD

**Issue by hybridherbst** [gkjohnson/three-gpu-pathtracer#154]
**Describe the bug**

Seems that there isn't much error handling / guarding against other types of materials that may be in an existing scene already - 
for example, using a [`MeshNormalMaterial`](https://threejs.org/docs/#api/en/materials/MeshNormalMaterial) anywhere will cause an exception in `MaterialStructUniform.updateFrom`.

Such materials could already be present in scenes that people want to render with three-gpu-pathtracer, and currently there's also no actionable log – I found that this material is causing issues by adding a log here
![image](https://user-images.githubusercontent.com/2693840/169407301-4a7d7a79-0081-4bd7-a58e-82a1124f77f8.png)

I also looked into fixing this myself, but MaterialStructUniform seems to have disappeared on latest master so not quite sure where to start / what other changes might happen before another release :)

**Expected behavior**

Renderer ignores objects whose materials can't be used instead of throwing an exception and stopping.

**Platform:**

 - Three.js version: r140
 - Library version: 0.0.2

**Comment by samevision** [comment]
It seems that this problem is already on the list: #127

**Comment by hybridherbst** [comment]
Thanks, I didn't see that! Closing as duplicate

**Comment by gkjohnson** [comment]
@hybridherbst thanks for the report! The material uniform code is now in the MaterialsTexture.js file. I think everything has reasonable defaults now but if you could take a look id appreciate it. Then we can close the other issue, too.

https://github.com/gkjohnson/three-gpu-pathtracer/blob/main/src/uniforms/MaterialsTexture.js
