### ISSUE TITLE
Add branch for perfectly specular reflection / smoother surface specularity

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/three-gpu-pathtracer#161]
The GGX function does not behave well at at small tight values and incurs floating point error artifacts meaning we have to keep a small value to avoid them which blurs our final result. Instead if a roughness value is below a certain threshold we could interpolate towards the perfect vector to avoid the artifacts and get perfect specularity.

See progressively blurring reflections here with 0 roughness:
![170802001-5f5b9123-1122-435c-8898-cc85f95af141](https://user-images.githubusercontent.com/734200/170802951-4662e709-fd55-465d-90bb-9639d00cc366.jpg)

**Comment by gkjohnson** [comment]
Just setting the ray is not enough - the PDF function must be adjusted, as well. It's possible the PDF function is where the precision issues are cropping up

**Comment by bhouston** [comment]
I can put a bounty on an accepted PR that fixes this issue of $250 USD sponsored by @Threekit.

**Comment by bhouston** [comment]
Be aware that there is now a pending PR for this!  https://github.com/gkjohnson/three-gpu-pathtracer/pull/171
