### ISSUE TITLE
Sheen material property

### ISSUE THREAD

**Issue by bhouston** [gkjohnson/three-gpu-pathtracer#167]
**Is your feature request related to a problem? Please describe.**

In adhering to the goal of reproducing the full glTF PBR Next model, one of the currently missing material properties is sheen.  It is primarily used for cloth.

![cushion](https://user-images.githubusercontent.com/588541/171766562-79820feb-1d2d-45b5-9f8e-d898dbf994c6.png)

**Describe the solution you'd like**

Parameters and behavior should follow glTF KHR_materials_sheen extension: 

https://github.com/KhronosGroup/glTF/tree/a9cd1cb657587b590b6f95c8654038a4e9d66596/extensions/2.0/Khronos/KHR_materials_sheen 

The properties required to support are:

|                                  | Type                                                                            | Description                            | Required                       |
|----------------------------------|---------------------------------------------------------------------------------|----------------------------------------|--------------------------------|
|**sheenColorFactor**                   | `array`                                                                         | The sheen color in linear space        | No, default: `[0.0, 0.0, 0.0]` |
|**sheenColorTexture**         | [`textureInfo`](/specification/2.0/README.md#reference-textureInfo)             | The sheen color (RGB).<br> The sheen color is in sRGB transfer function | No               |
|**sheenRoughnessFactor**               | `number`                                                                        | The sheen roughness.                   | No, default: `0.0`             |
|**sheenRoughnessTexture**         | [`textureInfo`](/specification/2.0/README.md#reference-textureInfo)             | The sheen roughness (Alpha) texture. | No               |

**Comment by bhouston** [comment]
I am pleased to be able to put a bounty of $500 USD on an accepted PR that implements the official glTF sheen extension in this path tracer.

**Comment by richardassar** [comment]
Taking a look at this, I recall the paper [A Practical Microcylinder Appearance Model for Cloth Rendering](http://graphics.ucsd.edu/~henrik/papers/practical_microcylinder_appearance_model_for_cloth_rendering.pdf) which may or may not be useful here.

**Comment by richardassar** [comment]
Results from a quick first pass at this. 

**Highlights at grazing angles:**
![Screenshot 2022-06-23 at 00-01-46 Material Orb Path Tracing](https://user-images.githubusercontent.com/868396/175168821-8e4fde49-dc2d-4696-b045-eb2c7ac6689c.png)

**Custom sheen color:**
![Screenshot 2022-06-23 at 00-26-40 Material Orb Path Tracing](https://user-images.githubusercontent.com/868396/175174819-c2cc29e2-7db6-4a9b-aaee-5c9899c0f48a.png)

![Screenshot 2022-06-23 at 00-33-21 Material Orb Path Tracing](https://user-images.githubusercontent.com/868396/175177009-da0c55f8-647e-4a53-83d9-7d9c46d6a27a.png)

**Comment by richardassar** [comment]
Also, incorporating this recent set of changes prompts a `bsdfMix` and `bsdfBlend` approach as it could be more modular and configurable

I'm working on each of these recent feature requests (iridescence, sheen, clear coat) in separate branches but it might make sense to coalesce them into a single PR with the bsdf mix/blend approach. I'll update as to whether this is necessary or makes sense here.

**Comment by richardassar** [comment]
Showing the effect on the SheenCloth model from glTF-Sample-Models, there's also SheenChair which I'll test.

**Without Sheen**
![Screenshot 2022-06-23 at 06-31-24 Material Orb Path Tracing](https://user-images.githubusercontent.com/868396/175223248-d72795ec-80e2-4389-af07-51448c1306fb.png)

![Screenshot 2022-06-23 at 06-15-13 Material Orb Path Tracing](https://user-images.githubusercontent.com/868396/175223770-11f5f3d3-96aa-4952-89fc-293870d7efe7.png)

**With Sheen**
![Screenshot 2022-06-23 at 06-30-19 Material Orb Path Tracing](https://user-images.githubusercontent.com/868396/175223347-074bbc48-db0e-4d8f-846f-e42622ac68e3.png)

![Screenshot 2022-06-23 at 06-17-17 Material Orb Path Tracing](https://user-images.githubusercontent.com/868396/175223837-daf893c7-b20a-4bfb-affa-efc40a3ee7ab.png)

**Custom Sheen Color**
![Screenshot 2022-06-23 at 06-37-38 Material Orb Path Tracing](https://user-images.githubusercontent.com/868396/175223446-30205b33-af0d-4ef8-8ea7-d4281b17a3bc.png)

![Screenshot 2022-06-23 at 06-21-31 Material Orb Path Tracing](https://user-images.githubusercontent.com/868396/175223862-8d3c2880-3aaa-4f53-88f2-f666beaf462f.png)

**Low Light Setting**
![Screenshot 2022-06-23 at 06-24-31 Material Orb Path Tracing](https://user-images.githubusercontent.com/868396/175223685-7a0e344f-9bfa-441d-9497-a9d3f13e7fed.png)

Just adding the sheen contributions to the bsdf pdf, color and direction for now, but with the correct bsdfMix I think this could be corrected to properly sit on top of the underlying metalness/roughness bsdf.

The model comes with a sheen color + sheen roughness texture, which I'll load and demonstrate next.

**Comment by richardassar** [comment]
A more plastic looking material, with a little higher metalness.
![Screenshot 2022-06-23 at 07-13-50 Material Orb Path Tracing](https://user-images.githubusercontent.com/868396/175228272-8896198d-a02b-4a52-9f4a-5a7788c090cc.png)

**Comment by richardassar** [comment]
Implemented the weighted `bsdfMix` approach so now the effect can be made more subtle and chained with other effects.

![Screenshot 2022-06-23 at 11-31-50 Material Orb Path Tracing](https://user-images.githubusercontent.com/868396/175279650-0ec6db4b-96c8-442c-b202-c2990bee58a8.png)

**Comment by richardassar** [comment]
Here are some previews of models using sheen from [glTF-Sample-Models](https://github.com/KhronosGroup/glTF-Sample-Models).

I had to hook up a `GLTFMaterialsSheenExtension` as THREE.js still doesn't support this extension, I added support for the `sheenColorMap` and `sheenRoughnessMap` giving us now the ability to load glTF files using the `KHR_materials_sheen` extension.

Hooking everything up gives us the following:

**SheenChair.glb**
![Screenshot 2022-06-23 at 15-02-48 Material Orb Path Tracing](https://user-images.githubusercontent.com/868396/175321570-389996ca-dce7-4828-bd94-d6e563a67f72.png)

See [here](https://threejs.org/examples/webgl_loader_gltf_sheen.html) for rasterized reference.

**SheenCloth.glb**
![Screenshot 2022-06-23 at 14-57-41 Material Orb Path Tracing_cropped](https://user-images.githubusercontent.com/868396/175322417-3ea13bff-e8ac-4896-b084-1933c90909b3.png)

This one masks the sheen on the black regions of the pattern. I had to tone down the sheen effect on this one using the `brdfMix` mentioned previously as it was a bit much, we can expose this as an extra parameter which defaults to `1.0`.

**Comment by richardassar** [comment]
The [README.md](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/SheenChair/README.md) for the SheenChair model shows correspondence with what I have when turning `FEATURE_SHEEN` on and off.

**FEATURE_SHEEN: 1**
![Screenshot 2022-06-23 at 17-19-13 Material Orb Path Tracing](https://user-images.githubusercontent.com/868396/175347386-63748f8a-d3e8-467f-84e1-477b31371dc3.png)

**FEATURE_SHEEN: 0**
![Screenshot 2022-06-23 at 17-19-23 Material Orb Path Tracing](https://user-images.githubusercontent.com/868396/175347472-6bb62493-3b83-41b8-9c8c-c718dc2bd7b3.png)

**Comment by richardassar** [comment]
The README also makes mention of `KHR_materials_variants` which would be nice to support also.

**Comment by bhouston** [comment]
> The README mentions KHR_materials_variants which would be nice to support also.

This is actually supported at the Three.js data loading level, no need to support it within this renderer itself. :). At least I've seen Three.js projects that make use of that extension already in the wild.

> Also, incorporating this recent set of changes prompts a bsdfMix and bsdfBlend approach as it could be more modular and configurable.

There is a very clear hierarchy on how to incorporate all these effects.  It is actually a fixed system these days for these physical properties.  While there isn't a chart on the glTF website that shows it, here is one from the "Autodesk Standard Surface" Which is near equivalent to the glTF material model:

![diagram_closure_mix](https://user-images.githubusercontent.com/588541/175423074-efa02275-3253-44b9-8199-8a03e58a57a1.svg)

https://autodesk.github.io/standard-surface/

The flexibility these days usually happens with arbitrary graphs which determine the properties that feed into the material system.  I think the emerging standard is MaterialX and eventually it would be nice for both Three.js and this path tracer to support it -- but interestingly it doesn't actually change the base BRDF tree we are creating by implementing these glTF material extensions.

**Comment by richardassar** [comment]
> > The README mentions KHR_materials_variants which would be nice to support also.
> 
> This is actually supported at the Three.js data loading level, no need to support it within this renderer itself. :). At least I've seen Three.js projects that make use of that extension already in the wild.

From what I could see this isn't supported, at least not to our needs, the [PR](https://github.com/mrdoob/three.js/commit/ddccc2727bfc289bf6c553c0779e7746db9edd04) which added `KHR_materials_variants` touches `sheenTint` and `sheenRoughness`. Instead I register a corrected `GLTFMaterialsSheenExtension` that populates `sheenColor`, `sheenRoughness`, `sheenColorMap` and `sheenRoughnessMap`, and pushes the `parser.assignTexture` results into `pending` that is passed on to the returned `promise`. Without this there isn't enough to fully satisfy this extension's requirements.

> 
> > Also, incorporating this recent set of changes prompts a bsdfMix and bsdfBlend approach as it could be more modular and configurable.
> 
> There is a very clear hierarchy on how to incorporate all these effects. It is actually a fixed system these days for these physical properties. While there isn't a chart on the glTF website that shows it, here is one from the "Autodesk Standard Surface" Which is near equivalent to the glTF material model:
> 
> ![diagram_closure_mix](https://user-images.githubusercontent.com/588541/175423074-efa02275-3253-44b9-8199-8a03e58a57a1.svg)

Thanks, this is a very informative diagram. The one issue I have with the glTF specs is that they're suited only to BRDF, providing BSDF / PDF and Evaluate for the path tracing case would be good

> 
> https://autodesk.github.io/standard-surface/
> 
> The flexibility these days usually happens with arbitrary graphs which determine the properties that feed into the material system. I think the emerging standard is MaterialX and eventually it would be nice for both Three.js and this path tracer to support it -- but interestingly it doesn't actually change the base BRDF tree we are creating by implementing these glTF material extensions.

I was actually going to suggest exactly this, being a node/graph fan myself (see [VisionMachine](https://www.youtube.com/watch?v=3LNsIErxPZw)). With the introduction of `bsdfMix` now it would be possible to support render graphs by a code generation approach, each material could reference a graph by ID and then you switch and select e.g. `graphBsdf0` and so on (of course OpTypePointer>OpTypeFunction would be nicer) - I'm quite tempted to experiment with laying initial foundations for this as part of the iridescence/sheen/clearcoat features.

**Comment by richardassar** [comment]
In the following papers layered BRDFs are achieved by baking them into Fourier bases, providing efficiency and accuracy. It seems like something that would be easy to achieve with the node/graph based representation, and these could be baked on the GPU prior to the main scene or before rendering an animation.

[A Comprehensive Framework for Rendering Layered Materials](https://rgl.s3.eu-central-1.amazonaws.com/media/papers/Jakob2014Comprehensive_2.pdf) 
The paper is discussed in this [project report](https://alexus37.github.io/projects/layeredMaterials/layeredMaterials.html), which shows some side-by-side comparisons.

[Arbitrarily Layered Micro-Facet Surfaces](https://www.cg.tuwien.ac.at/research/publications/2007/weidlich_2007_almfs/weidlich_2007_almfs-paper.pdf)

This is more relevant for the clear coat issue but I'm mentioning it in relation to graphs.

https://raytracing-docs.nvidia.com/mdl/introduction/index.html#mdl_introduction#distribution-function-modifiers-and-combiners also discusses layering and the heuristics, for example the `fresnel_layer`, are used as MIS heuristics in [BRDF Blending in Path Tracing with Multiple Importance Sampling](https://theses.fh-hagenberg.at/system/files/pdf/Legmaier18.pdf).

**Comment by bhouston** [comment]
I don't know if this helps but here is more information on the origins and goals of the glTF PBR Next model.

Starting in the mid 2010s the VFX indsutry started to develop a strong formalized Uber BRDF model.  This really started with [Disney's PBR model by Burley](https://pdfs.semanticscholar.org/3f4b/29a0cc51f1ba8baaf99asc008f3acf18d04df.pdf).  Then it come to wider usage in the high end VFX industry with Andres Langland's [alSurface model for Arnold](https://leegriggs.files.wordpress.com/2015/07/alsurface.pdf).

Then every major 3D company decided to standardize their own version of these Uber shaders:

* [Autodesk Standard Surface](https://autodesk.github.io/standard-surface/)
* [Dassault Enterprise PBR](https://dassaultsystemes-technology.github.io/EnterprisePBRShadingModel/)
* [Adobe Standard Material](https://substance3d.adobe.com/documentation/s3d/files/225969597/225969613/1/1647027222890/Adobe+Standard+Material+-+Specification.pdf)
* [NVIDIA MDL](https://www.nvidia.com/en-us/design-visualization/technologies/material-definition-language/)

There are similar material models in Unreal Engine and Unity as well, but they are not as formalized as the above.  Blender's "[Principled BRDF](https://docs.blender.org/manual/en/latest/render/shader_nodes/shader/principled.html)" is basically the same as these with minor tweaks.

To try to help with the situation, the glTF PBR Next extensions are trying to find/distill the commonalities between these more proprietary systems.  Adobe, Dassault, Autodesk, Unreal Engine and NVIDIA are involved in the glTF PBR Next standardization process.

This is the reason why I have specified all material improvements for this renderer as these glTF extensions.  They are the distilled common best practices for transferable Uber shaders.  Basically if we implement these, this renderer can be compatible with the ecosystem of Autodesk, Adobe, Dassault, and Unreal Engine and Unity.

I think that for the foreseeable future (5-10 years) these uber BRDFs are going to be the main material definition system.  Of course there will be slow addition of new features to the common specification as things move forward, but it is generally tweaks and small additions, rather than major changes.

I found this on the glTF website -- a similar BRDF blending tree to the Autodesk Standard Surface one - although I think it may be incomplete: 

![pbrext](https://user-images.githubusercontent.com/588541/175557788-d61e0caf-6115-4c02-ab40-f1a2cb058029.png)

[From here](https://github.com/KhronosGroup/glTF/blob/0343ff13ba7f3a4b717a235aa75b45655ab512c7/extensions/README.md#user-content-pbr-material-extensions)

I do not think because of the current stage of the industry that we have to expose the BRDF mixing nodes to the user any time soon.  I think that we can hide them under an Uber Material interface as is now standard practice.

And if/went we add MaterialX support, it will just be for creating graphs that feed into the properties of the Uber Material, rather than remixing the BRDFs themselves in arbitrary fashions.  I wrote up a draft of this a few years ago [TK_MATERIAL_GRAPH](https://docs.google.com/document/d/1Y6JFE2FV164IFDe7_cYhp2gzhSapB76fUNPgmsI6DDY/edit#heading=h.ptayfzbvu0py)...

**Comment by richardassar** [comment]
Changes in https://github.com/gkjohnson/three-gpu-pathtracer/pull/205, ready for review.
