### ISSUE TITLE
Clear Coat material property

### ISSUE THREAD

**Issue by bhouston** [gkjohnson/three-gpu-pathtracer#168]
**Is your feature request related to a problem? Please describe.**

In adhering to the goal of reproducing the full glTF PBR Next model, one of the currently missing material properties is clear coat.  It is primarily used for lacquers, varnishes as well as the clear coat on cars or on ceramics.

**Describe the solution you'd like**

![khr-materials-clearcoat](https://user-images.githubusercontent.com/588541/174065969-5df8f8fe-b226-4821-a6bc-c3ddb13fc73a.png)

Parameters and behavior should follow glTF KHR_materials_clearcoat extension: 

https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_materials_clearcoat 

The following parameters are contributed by the `KHR_materials_clearcoat` extension:

|                                  | Type                                                                            | Description                            | Required             |
|----------------------------------|---------------------------------------------------------------------------------|----------------------------------------|----------------------|
|**clearcoatFactor**               | `number`                                                                        | The clearcoat layer intensity.         | No, default: `0.0`   |
|**clearcoatTexture**              | [`textureInfo`](https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#reference-textureinfo)             | The clearcoat layer intensity texture. | No                   |
|**clearcoatRoughnessFactor**      | `number`                                                                        | The clearcoat layer roughness.         | No, default: `0.0`   |
|**clearcoatRoughnessTexture**     | [`textureInfo`](https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#reference-textureinfo)             | The clearcoat layer roughness texture. | No                   |
|**clearcoatNormalTexture**        | [`normalTextureInfo`](https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#reference-material-normaltextureinfo) | The clearcoat normal map texture.      | No                   |

**Comment by bhouston** [comment]
I am pleased to be able to put a bounty of $250 USD on an accepted PR that implements the official glTF clear coat extension in this path tracer.

**Comment by richardassar** [comment]
Taking a look at this also, gathered some resources, existing implementations etc.

**Comment by richardassar** [comment]
Here's an update on this. 

Apologies that it took a bit longer, I was juggling some other things and also was cross-referencing with [GLSL-PathTracer](https://github.com/knightcrawler25/GLSL-PathTracer) and [dspbr-pt](https://github.com/DassaultSystemes-Technology/dspbr-pt) which also support sheen and iridescence.

![Screenshot from 2022-07-05 08-27-11_r](https://user-images.githubusercontent.com/868396/177275325-0fadb132-f535-400c-9228-3530799705ef.png)
^ Taken from [this THREE.js example scene](https://github.com/mrdoob/three.js/blob/master/examples/webgl_materials_physical_clearcoat.html). There's a slight issue with the carbon fibre sphere, when the normals of the underlying layer are of a certain value the clearcoat layer is completely attenuated, this should be easy enough to track down.

![Screenshot from 2022-07-05 08-33-18](https://user-images.githubusercontent.com/868396/177274990-8c5c8863-a840-478f-9edb-7c990414a66e.png)
^ From [glTF-Sample-Models](https://github.com/KhronosGroup/glTF-Sample-Models)

For comparison here is the output of [dspbr-pt](https://github.com/DassaultSystemes-Technology/dspbr-pt) on the same above scene.

![Screenshot from 2022-07-05 08-50-38](https://user-images.githubusercontent.com/868396/177277949-f2c8d863-5b0f-45a5-b158-a0e2b67be150.png)

I still need to add `clearcoatTexture` and `clearcoatRoughnessTexture`, for which I will need to find or create some scenes that actually utilise these fields.

I think it's best to submit a PR with iridescence + sheen + clearcoat together as it means I can merge all of the feature branches locally and avoid any mess, so I'll proceed to work on that now.

**Comment by bhouston** [comment]
Beautiful work!

**Comment by richardassar** [comment]
Thanks Ben.

**Comment by richardassar** [comment]
Opted to submit these separately, changes are in https://github.com/gkjohnson/three-gpu-pathtracer/pull/203 ready for review.

**Comment by gkjohnson** [comment]
Just merged #203!
