### ISSUE TITLE
Precision issues when camera is far away

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/three-gpu-pathtracer#178]
Related to #114 
Related to https://github.com/google/model-viewer/pull/3496

When the camera is far away (xyz values > ~1000 or so) there seem to be precision issues in the positioning of the ray origins resulting in "chunky" or pixelated looking images. Scaling the scene and values down to be within [-1, 1] fixes the issues.

Not exactly sure what can be done about this other than recommending that people scale the scene as appropriate.

Seen on second generation Mac M1 laptop.

Example:

![image](https://user-images.githubusercontent.com/734200/173278325-c76bb864-28e3-4a1a-ab64-c1f0036e5be6.png)

**Comment by gkjohnson** [comment]
Zooming out significantly in a demo results in the same kind of artifacts:

![image](https://user-images.githubusercontent.com/734200/174242012-d9c94206-66e4-4eff-b34b-e2285247f871.png)

I wonder if we should apply a translation / scale factor to the camera transform and model to keep the camera in a relative "safe" numeric zone for rendering.

**Comment by mrxz** [comment]
I took a look at the issue and it seems that computing the `rayDirection` differently for the perspective camera resolve the issue. There might still be precision issues to some extent, but at least the buggy is no longer blocky (well, it is, but that's intended :smile: ) and zooming out doesn't cause the environment to show artifacts.

See #190 for the change.

> I wonder if we should automatically apply a translation / scale factor to the camera transform and model to keep the camera in a relative "safe" numeric zone for rendering.

Scaling the model is a bit tricky IMO. With different light types being introduced, the light should be 'scaled' as well, which isn't the default behaviour in glTF or Threejs. Given that glTF is the prominent format, I would also say the scale of the scene should be in meters. So if any scaling needs to be done, it should be on the shader side of things, or at least, completely transparent to the user.

It might be a good idea to have test-cases that demonstrate the bounds of what still renders correctly and where precision issues become an issue (too large and too small). Perhaps a simple scene that is scaled up/down. This not only gives the bounds users should try to stay within, but could also help detect regressions or improvements.

**Comment by gkjohnson** [comment]
Thanks for the fix - it's a great improvement. Now the precision issues will be a result of ray origin calculations but they seem to be less of an issue an start showing up closer to ~400,000-500,000 units away from the origin which I think is reasonable for now. I think we can wait until there are other issues before investing in more complex solutions to this. Thanks again!
