### ISSUE TITLE
SpotLight IES profile support

### ISSUE THREAD

**Issue by bhouston** [gkjohnson/three-gpu-pathtracer#181]
**Is your feature request related to a problem? Please describe.**

It would be nice to support IES profiles when rendering spot lights.

Here is a library of IES profiles: [https://ieslibrary.com/en/home](https://t.co/N2yIJ0geJd)

Here is example code for parsing an IES profile: https://gist.github.com/bhouston/f2d1935aeabe2630d20c10390ce17cb5

I believe that for the majority of cases a simple 1D texture can represent IES profile data.

**Describe the solution you'd like**

It would be nice to be able to load an IES profile into a texture and then use that texture as a modulator on SpotLights.  I think it is important to separate the IES profile loading from the texture setting on the spot lights to keep everything simple.

CC: @richardassar

**Comment by bhouston** [comment]
@Threekit is pleased to offer a $250 USD bounty for an accepted PR that implements the feature described in this issue.

**Comment by richardassar** [comment]
In UE you can add them to point and rectangular area lights also, as shown [here](https://docs.unrealengine.com/5.0/en-US/using-ies-light-profiles-in-unreal-engine/).

It seems like something that should be applied to all lights, optionally, with spotlights just masking one half of the profile.

**Comment by gkjohnson** [comment]
Thanks @bhouston! I'm assuming it's okay if we include your IESLoader in this project?

**Comment by bhouston** [comment]
yes. :)

**Comment by richardassar** [comment]
Integrated the IESLoader from @bhouston. 

Required only minimal changes such as changing the texture type from `UnsignedByteType` to `FloatType`, as the precision is necessary, and changing the texture format from `LuminanceFormat` to `RedFormat` to avoid WebGL warnings/errors.

The textures are packed by the newly introduced `IESProfilesTexture`, a `WebGLArrayRenderTarget`, which is stored as a `PhysicalPathTracingMaterial` uniform. Spot lights may optionally use the profiles, falling back to the default behavior when no profile is selected. There's an extra `radius` parameter which can be used to influence shadow softness.

Just need to tidy the code, make a nicer demo scene and  then submit the PR.

![Screenshot 2022-06-14 at 08-33-55 Material Orb Path Tracing](https://user-images.githubusercontent.com/868396/173520092-c5da8b73-2b51-4ad8-a4e7-212b72d8f516.png)

![Screenshot 2022-06-14 at 08-30-41 Material Orb Path Tracing](https://user-images.githubusercontent.com/868396/173520097-b67900ac-0c26-4555-b648-2e00cd2a5188.png)

![Screenshot 2022-06-14 at 08-29-10 Material Orb Path Tracing](https://user-images.githubusercontent.com/868396/173520102-d814c6ae-6624-4ed4-b838-8add7cd7aaf9.png)

![Screenshot 2022-06-14 at 08-28-14 Material Orb Path Tracing](https://user-images.githubusercontent.com/868396/173520111-c84cadb4-e2e6-4579-8713-7a988d71224c.png)
