### ISSUE TITLE
White Artifacts on Glancing Edges in v0.0.5

### ISSUE THREAD

**Issue by joewhatkins** [gkjohnson/three-gpu-pathtracer#215]
**Describe the bug**

Release 0.0.5 introduced an issue where we get strange bright segments on glancing angles on our meshes.

![image](https://user-images.githubusercontent.com/85718573/180146525-da7e8f9e-329e-44ae-8ed9-57a6b72c43b6.png)

On inspection of some of the examples in this repo, we noticed that there are similar artifacts on the skinnedMesh example.

![image](https://user-images.githubusercontent.com/85718573/180147449-ec2649ff-2e44-4270-a8c7-96e30fa256e7.png)

I ran the same examples after downgrading to 0.0.4 and there weren't any artifacts.

![image](https://user-images.githubusercontent.com/85718573/180147610-e10f7b8e-777e-4963-9530-ad769ceff1e0.png)

![image](https://user-images.githubusercontent.com/85718573/180147984-3fde1122-6343-4118-9d44-d72b76b5dc06.png)

Running a bisect identified [e4e275746877aea2579bc6a29792a0137da5bb70](https://github.com/gkjohnson/three-gpu-pathtracer/commit/e4e275746877aea2579bc6a29792a0137da5bb70) as the breaking commit - specifically the change to passing wo to ggxPDF instead of wi in specularPDF. This was originally implemented as part of #174 to add support for area lights and fix issues with a divergence between MIS and non-MIS rendering. 

I tried reading the referenced materials but it seems like the implementaitons in three-gpu-pathtracer diverge from them in a few different ways. I looked at other sources explaining specular PDF methods and found a few other implementations - one of which set the specular PDF to zero if the product of the normals of the outgoing direction and incident direction is less than zero. I'm not exactly an expert on PBR so please let me know if there's a more principled solution to this.

It's too late here for me to parse out exactly what this means, but implementing it locally seemed to (mostly) resolve the issue while still maintaining the expected area light behavior.

**0.0.4 (working as expected)**
![image](https://user-images.githubusercontent.com/85718573/180150389-c34cac36-0262-45ee-a08e-e8eb349a3ad5.png)

**0.0.5 without fix**
![image](https://user-images.githubusercontent.com/85718573/180150085-5c400349-21d2-4f8e-9ca4-8304dbf6b3f5.png)

**0.0.5 with fix**
![image](https://user-images.githubusercontent.com/85718573/180150658-0e572da2-9459-49a6-8190-78b0ae648203.png)

You can see that there are still _slight_ white edges alongside the bottom of the arm and edge of the tire, but the edges along the mirror have disappeared entirely.

It's also possible this is due to issues with our meshes and the T-Rex skinned mesh, given none of the other examples seem to have these problems.

**Expected behavior**

Ideally behavior is the same as in 0.0.4 while maintaining properly-working area lights.

**Screenshots and Repro Model**

Add screenshots and a gltf model to help explain your problem (drag and drop).

**Platform:**

 - Device: Desktop
 - OS: Ubuntu
 - GPU: NVidia
 - Browser: Chrome
 - Three.js version: r141
 - Library version: v0.0.5

**Comment by setpixel** [comment]
Hi @gkjohnson! @joewhatkins and I are working together. I spotted the rendering regression. It would be cool to set up a test that renders the fidelity tests comparing renders to previous release renders. I think it would be a useful tool to spot check for regressions and improvements.

**Comment by gkjohnson** [comment]
Thanks @joewhatkins! I've noticed a few issues, as well, and it's on my list to take a look at them (#76, #210). But it's always helpful to have more eyes on this stuff! If you have improvements to make then feel free to make a PR and we can take a look! There are definitely still things to fix.

> I spotted the rendering regression. It would be cool to set up a test that renders the fidelity tests comparing renders to previous release renders. I think it would be a useful tool to spot check for regressions and improvements.

I'm working on #214 to help with this. Unfortunately I can't get it working on the Github Actions CI but at least it will be able to be run locally.
