### ISSUE TITLE
Spotlight Reflections include dark spots

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/three-gpu-pathtracer#242]
I noticed this when updating the Spotlight example in #239. In a reflective surface there's a black spot at the center of where the spotlight should be hit directly:

<img width="769" alt="image" src="https://user-images.githubusercontent.com/734200/181620301-cfd5fcd3-7789-4d32-b645-7a0c4a8275ef.png">

cc @richardassar not sure if you have any ideas on this?

**Comment by richardassar** [comment]
I'll take a look at this, I have an idea on what might be the cause.

**Comment by gkjohnson** [comment]
It seems this is caused by the material PDF sample for the ray hitting the light returning a particularly hight value which dwarfs the light PDF which is a constant 1.0 at the moment. It seems we need to figure out how to appropriately handle the PDF for punctual lights.

```glsl
float lightMaterialPdf = bsdfResult( outgoing, clearcoatOutgoing, normalize( invBasis * lightSampleRec.direction ), normalize( clearcoatInvBasis * lightSampleRec.direction ), surfaceRec, sampleColor );
```

PBR Book here may help:

https://www.pbr-book.org/3ed-2018/Light_Sources/Point_Lights

**Comment by gkjohnson** [comment]
The pattern is caused by the **misWeight** value:

<img width="653" alt="image" src="https://user-images.githubusercontent.com/734200/208245398-7580d4e7-e8ed-4a53-8d00-f0bd4f0f3716.png">

And the **misWeight / lightPdf** value:

<img width="615" alt="image" src="https://user-images.githubusercontent.com/734200/208245482-9f0eefff-0d48-4a4a-8631-0c906dd987cb.png">
