### ISSUE TITLE
Multiple views

### ISSUE THREAD

**Issue by lucassel** [gkjohnson/three-gpu-pathtracer#250]
Hi everybody!

I've been trying to render the vanilla [multiple views example](https://threejs.org/examples/?q=multiple#webgl_multiple_views) ([source](https://github.com/mrdoob/three.js/blob/master/examples/webgl_multiple_views.html)) with the PathTracingRenderer and I have made some strides in my `animate` loop but I haven't found a way of setting the scissorTest on the PTR. It doesn not appear to fully extend the three-js raster renderer in that regard.

Has anybody figured out a way of only rendering a portion of the canvas, based on a view, with the PTR? 

I do not think having multiple renderers is a satisfactory, nor efficient solution 😄

**Comment by gkjohnson** [comment]
The PathTracingRenderer is not designed to support shifting views the way they do in that demo. The scissor test is used internally to support tiled renderering, as well. The simple solution is to create multiple pathtracer renderers and composite the final targets where you need in the final frame. Do you mind explaining your use case? Other solutions to simplify this or support it more directly would require some rearchitecting I'm not prepared to do at the moment.

**Comment by lucassel** [comment]
Hey, thanks for your fast answer. I was able to work something out yesterday with multiple PathTraceRenderer instances. The usecase is a webpage with a gallery of product shots that are interactive clientside renders 👍 


Thank you for the amazing tool!
