### ISSUE TITLE
Question about three-gpu-pathtracer samples

### ISSUE THREAD

**Issue by chenxiaoleizi** [gkjohnson/three-gpu-pathtracer#258]
I am reading the three-gpu-pathtracer source code. In the example scene when we stop move or rotate the camera, the noise become less and less, the result quality become more and more high. I dont know how this implemented. I was thought when set `renderer.autoClear=false` can implement this, but when i comment the `renderer.autoClear=false`, nothing change. So how to combine the multiple samples to get the high quality result?

**Comment by gkjohnson** [comment]
The progressively higher and higher quality is achieved by averaging the value of samples over time. This is done by using normal blending and outputting a fragment with an alpha that is multiplied by `1 / sampleCount` - see [here](https://github.com/gkjohnson/three-gpu-pathtracer/blob/8b502b0d994ac61f3c550df9c1a2e0df8d8fec8e/src/materials/PhysicalPathTracingMaterial.js#L910) and [here](https://github.com/gkjohnson/three-gpu-pathtracer/blob/8b502b0d994ac61f3c550df9c1a2e0df8d8fec8e/src/core/PathTracingRenderer.js#L23-L34)

**Comment by chenxiaoleizi** [comment]
@gkjohnson The **PathTracingRenderer** use _fsQuad(FullScreenQuad) to render with the **PhysicalPathTracingMaterial**, and when set alpha to false outputting the result to `_primaryTarget`(RenderTarget), then we use the _primaryTarget as a texture for final result.

By set `autoClear = false` [here](https://github.com/gkjohnson/three-gpu-pathtracer/blob/8b502b0d994ac61f3c550df9c1a2e0df8d8fec8e/src/core/PathTracingRenderer.js#L96) before we render  _fsQuad , we can keep the last sample result, then the quality become higher and higher.

Is that right？

**Comment by gkjohnson** [comment]
That's correct. Setting autoClear to false allows us to retain the previous frames results.
