### ISSUE TITLE
MaterialsTexture: Vertex Array Buffer for Material Ids is too small

### ISSUE THREAD

**Issue by maciejNisztuk** [gkjohnson/three-gpu-pathtracer#269]
**Describe the bug**

I have main three scene with multiple meshes (>100), some of them have textures, some of them have plain materials (Phong and MeshStandardMats) without textures. For path-tracing I create a new scene and clone selected meshes to this new scene and switch the renderer to path-tracing one. During path-tracing scene creation, the generator messes the order of materials, assigning wrong materials/textures to different meshes. Everything work ok if scene contains less meshes (see screenshots). Some of the meshes contain transmission maps.

**Expected behavior**

The expected behaviour is that the textures/materials are assigned to correct meshes.

**Screenshots and Repro Model**
This is ok
![1](https://user-images.githubusercontent.com/83579350/194335174-b2a1a094-728b-4ca5-b676-ecc48f5945fd.jpg)
This scene is messed up
![2](https://user-images.githubusercontent.com/83579350/194335178-6919222b-13a2-46ee-9c86-5ea658bd913c.jpg)

**Platform:**

 - Device: Desktop
 - OS: Windows
 - GPU: NVidia
 - Browser: Chrome
 - Three.js version: 144
 - Library version: 0.6

**Comment by gkjohnson** [comment]
Helo! You'll need to provide an example model otherwise I won't be able to reproduce the issue or know what the project is supposed to look like.

**Comment by maciejNisztuk** [comment]
@gkjohnson Here is the sample model. It's gltf as some models have textures. As Github don't support this extension, you will find the file in the gdrive link:
https://drive.google.com/file/d/1TphSnNVXY4AU1M09Fm-yksk8K-UoLNlT/view?usp=sharing

**Comment by maciejNisztuk** [comment]
@gkjohnson can I send you the model to your github mail address?

**Comment by gkjohnson** [comment]
> @gkjohnson can I send you the model to your github mail address?

You should be able to zip the file and attach it to Github.

**Comment by maciejNisztuk** [comment]
> > @gkjohnson can I send you the model to your github mail address?
> 
> You should be able to zip the file and attach it to Github.

I would be very obliged if I could send you the model by e-mail. It is a matter of privacy of the data contained in the model.

**Comment by gkjohnson** [comment]
Understood -- feel free to email it to me.

**Comment by gkjohnson** [comment]
It looks like with many individual objects and materials the material ids per mesh get too large (> 255) and overflow the material id vertex buffer which uses a Uint8Array:

https://github.com/gkjohnson/three-gpu-pathtracer/blob/8a1ce8bab0b18fd5b480ab3d2a1de2c180f4be9c/src/utils/GeometryPreparationUtils.js#L8

The best solution here would be to use a typed array with enough precision to store the max material id. Ie use a Uint8Array when there are <= 255 materials needed. And a Uint16Array when there are > 255 materials.

Would you like to make a PR with the change?

**Comment by maciejNisztuk** [comment]
Thank's for your reply. Let me check on this :)
