### ISSUE TITLE
Memory leaks in PhysicalPathTracingMaterial and BlurredEnvMapGenerator

### ISSUE THREAD

**Issue by nine-fox** [gkjohnson/three-gpu-pathtracer#293]
Hi,

Based on the docs in https://threejs.org/docs/index.html#manual/en/introduction/How-to-dispose-of-objects, it reads:

Objects of type WebGLRenderTarget not only allocate an instance of WebGLTexture but also WebGLFramebuffers and WebGLRenderbuffers for realizing custom rendering destinations. These objects are only deallocated by executing WebGLRenderTarget.dispose().
 
So the renderTarget resources need dispose(). The following caused memory leak:
1) pmremTarget  in BlurredEnvMapGenerator is not disposed correctly.

// get the pmrem target
const pmremTarget = pmremGenerator.fromEquirectangular( texture );

2) RenderTarget2DArray is not disposed correctly in PhysicalPathTracingMaterial

textures: { value: new RenderTarget2DArray().texture },

My scenario is a bit complex, which needs allocation and deallocation lots of times, so I just found these 2 leaks. 

Hope it helps.

Thanks,
nine-fox

**Comment by gkjohnson** [comment]
Thanks for the report!

> pmremTarget in BlurredEnvMapGenerator is not disposed correctly.
> // get the pmrem target
> const pmremTarget = pmremGenerator.fromEquirectangular( texture );

This does look like an issue - would you like to make a PR with the fix? I think we can just dispose of the target at the end of the `generate` function.

> // get the pmrem target
> const pmremTarget = pmremGenerator.fromEquirectangular( texture );
>
> RenderTarget2DArray is not disposed correctly in PhysicalPathTracingMaterial
> textures: { value: new RenderTarget2DArray().texture },

This is more complicated, I think. Typically disposing of a material does not implicitly dispose of the uniforms. Its also possible to share things like the textures array between multiple materials. To that end I think it makes sense to require the user to dispose of each individual texture the way they'd need to for any other three.js material. But I'd be happy to hear other thoughts!

**Comment by nine-fox** [comment]
> Thanks for the report!
> 
> > pmremTarget in BlurredEnvMapGenerator is not disposed correctly.
> > // get the pmrem target
> > const pmremTarget = pmremGenerator.fromEquirectangular( texture );
> 
> This does look like an issue - would you like to make a PR with the fix? I think we can just dispose of the target at the end of the `generate` function.
> 
> > // get the pmrem target
> > const pmremTarget = pmremGenerator.fromEquirectangular( texture );
> > RenderTarget2DArray is not disposed correctly in PhysicalPathTracingMaterial
> > textures: { value: new RenderTarget2DArray().texture },
> 
> This is more complicated, I think. Typically disposing of a material does not implicitly dispose of the uniforms. Its also possible to share things like the textures array between multiple materials. To that end I think it makes sense to require the user to dispose of each individual texture the way they'd need to for any other three.js material. But I'd be happy to hear other thoughts!

Thanks for your reply!
1) Due to China GreatWall, not sure if I can do PR, will try later.
2) I think you are right, we need user to determine whether dispose textures or not. However, in current implementation, there is *no way* to clean it, unless to do a hack method. I would suggest to expose the dispose method.

Today I found another memory leak in PhysicalPathTracingMaterial. There is no way to dispose the followings.

				normalAttribute: { value: new FloatVertexAttributeTexture() },
				tangentAttribute: { value: new FloatVertexAttributeTexture() },
				uvAttribute: { value: new FloatVertexAttributeTexture() },
				colorAttribute: { value: new FloatVertexAttributeTexture() },
				materialIndexAttribute: { value: new UIntVertexAttributeTexture() },

**Comment by nine-fox** [comment]
I did some investigation on three.js texture's dispose(). Even I call texture.dispose(), I can still render the scene with that disposed texture. In WebGLTextures.js, disposed textures will recreate and reuse again.

If it works like that, would it be better to dispose all these textures in dispose method, even it is still in use? I can not find any harm to do this.

**Comment by gkjohnson** [comment]
> Today I found another memory leak in PhysicalPathTracingMaterial. 

I see this as the same issue as 2. you mention the first post. But it's not the case that you can't dispose of the texture uniforms - it's just a ShaderMaterial, after all, so they can be disposed of like any three.js uniform. The textures can be disposed like so:

```js
const material = new PhysicalPathTracingMaterial();
material.uniforms.normalAttribute.value.dispose()
material.uniforms.textures.value.dispose();
// ...

// or access textures via convenience accessors
material.normalAttribute.dispose();
material.textures.dispose();
// ...
```

You can also use a loop to iterate over all uniforms to do this in a more generic way.

> Due to China GreatWall, not sure if I can do PR, will try later.

It would be great if you could make a PR for the blurred environment map pmrem texture - help here is always appreciated!
