### ISSUE TITLE
How to make faster render 

### ISSUE THREAD

**Issue by hexaAnkit** [gkjohnson/three-gpu-pathtracer#294]
i want to make rendering faster as possible

so user don't have to wait to see how scene will look like after best rendering with high resolution
so is any feature i can disable and show instant result for demo purpose that the  image will look similar after waiting some time, so user don't have to wait, they can get idea of scene, shadow and light 

Thank you !

**Comment by gkjohnson** [comment]
Hello! Improving performance and affording more control over it is something that is planned to have at some point but the priority is making sure the quality is correct.

One way to improve performance at the moment is to disable multiple importance sampling - but you'll want to blur the environment map first so the image still resolves in a reasonable amount of samples.
