### ISSUE TITLE
Long Term Tasks

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/three-gpu-pathtracer#3]
- Use data texture for material info packing
- Add checkerboard rendering
- Add support for sphere lights
- Add drag and drop support
- Stratified sampling
  - http://abdallagafar.com/publications/zsampler/
  - https://momentsingraphics.de/ToyRenderer4RayTracing.html
  - https://momentsingraphics.de/ToyRenderer3RenderingBasics.html#Stratified_random_numbers_blue_noise_
  - https://graphicscompendium.com/raytracing/19-monte-carlo
  - http://theinstructionlimit.com/unity-toy-path-tracer
  - https://www.reddit.com/r/GraphicsProgramming/comments/ox0lvm/reducing_fireflies_in_path_tracing/
- Remove white gap when resizing
  - Set the larger of the two dimensions given the aspect ratio to ensure the gap is filled
- "Shadow only" material that just passes through if no shadow is cast
- ~Support for alpha maps~
  - May require custom shader raycast code to check alpha on triangle hit.
- ~Improve cosine sampling _more_ (currently there are artifacts)~
  - https://graphics.pixar.com/library/OrthonormalB/paper.pdf

**Comment by DanielDoesDesign** [comment]
Is a threeJS "spotlight" considered a sphere light?
