### ISSUE TITLE
Basic example page crashes MacOS Safari.

### ISSUE THREAD

**Issue by ikeough** [gkjohnson/three-gpu-pathtracer#309]
**Describe the bug**

I am experiencing a crash on mac Safari v.15+ when running the path tracer in my application. As a test, I visited the [basic example page](https://gkjohnson.github.io/three-gpu-pathtracer/example/bundle/basic.html) and it experiences the same error: "A problem repeatedly occurred with..." I do not experience the same issue on Chrome or on iOS Safari.

**Expected behavior**

The path tracer should run without crashing the tab.

**Screenshots and Repro Model**

![image](https://user-images.githubusercontent.com/1139788/204159086-71965ce0-fd6a-4dd3-8381-a66641ca16b5.png)

**Platform:**

 - Device: Desktop
 - OS: MacOS Monterey 12.3.1
 - GPU: Radeon Pro 555
 - Browser: Safari
 - Three.js version: latest sample page version?
 - Library version: latest sample page version?

**Comment by ikeough** [comment]
Additional context...This is on a 5 year old MacBook Pro, so it's very possible that this is not worth tracking down if it's not happening on newer equipment. This works on iOS Safari on my iPhone SE and my iPad so I assume that it's not Safari, per se, but most likely a GPU issue. Happy to provide the Mac console crash dump if you really want to go into the weeds.

**Comment by gkjohnson** [comment]
Unfortunately without being able to reproduce the problem I won't be able to do a whole lot but feel free to add any error logs to the issue. I believe Safari v16 fixed a bug that was causing an issue previously -- is it no longer possible to update Safari on that mac to check?

If you'd like to dig in yourself I can give some pointers but I suspect it will come down to device-specific shader compilation issues.

**Comment by ikeough** [comment]
Safari 16 was the fix. What's really interesting is now everything looks great in Safari, but not so great (see #310) in Chrome. 
![image](https://user-images.githubusercontent.com/1139788/204346798-d1aeea8e-1a2d-4c28-b8d4-b6bb1077f39a.png)

**Comment by gkjohnson** [comment]
> but not so great (see https://github.com/gkjohnson/three-gpu-pathtracer/issues/310) in Chrome.

Might be something to report to Chrome, then. As you can imagine the pathtracer shader is fairly complex and I've found compiler / driver quirks in quite a few platforms.

It could also be reported to #62, as well, if you want to compare your machine specs.

**Comment by ikeough** [comment]
Yep. Looks like exactly the same errors. Basically no shadows in Chrome and botched reflections. I'll track there.
