### ISSUE TITLE
Materials using PBRSpecularGlossiness have roughness=0

### ISSUE THREAD

**Issue by ikeough** [gkjohnson/three-gpu-pathtracer#310]
**Describe the bug**

Our glTF pipeline generates glTFs using the `KHR_materials_pbrSpecularGlossiness` extension. Using three's glTF loader, the specular and glossiness values are, we assume, converted correctly into metallic/roughness components. Everything looks great. When we use the path tracer however, all materials seem to have a roughness set to 0. That is, they are fully reflective. In looking through our glTFs, I can see that we are not also setting the `pbrMetallicRoughness.roughnessFactor`, which is recommended to support both models. We should update this, but I would assume that three's gltf loader is doing the right thing and setting the roughness value to something other than 0 (1-glossiness as recommended in the spec). Can I get some guidance on what model is preferred and whether we have to take this up with the authors of the glTF loader?

**Expected behavior**

Materials that use the `KHR_materials_pbrSpecularGlossiness` in glTF should not have their roughness set to 0 when their glossiness is < 1.

**Screenshots and Repro Model**

![image](https://user-images.githubusercontent.com/1139788/204167495-e21085ab-2186-4b11-8b33-e527b0ec3b86.png)

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - GPU: Radeon
 - Browser: Chrome
 - Three.js 141
 - Library version: 0.0.7

**Comment by gkjohnson** [comment]
The SpecularGlossiness extension required a different shader in the glTFLoader. I didn't have any plans to support bit since it would require a lot of extra work for the same results but it will actually be removed from three.js in the next release, as well (https://github.com/mrdoob/three.js/pull/24950).

It sounds like there are tools to convert the SG model to metalness-roughness so I think using those are the best solution here.

**Comment by ikeough** [comment]
Thanks for the explanation. This is really good to know. We'll update our code to move to metalness-roughness.

**Comment by donmccurdy** [comment]
In case its helpful:

- [Converting glTF PBR materials from spec/gloss to metal/rough](https://www.donmccurdy.com/2022/11/28/converting-gltf-pbr-materials-from-specgloss-to-metalrough/)

The conversion to metal/rough can be done on the fly in javascript, but it's expensive — you'll be rewriting any metallic roughness textures.

**Comment by gkjohnson** [comment]
I imagine it should be able to be done on the GPU and be significantly faster, right? Thought that's harder to do in a node CLI and it's probably best to just work and store textures in the metal-rough model, anyway.

**Comment by donmccurdy** [comment]
For CLI purposes the CPU is plenty fast here, but yes — GPU or WASM SIMD would speed things up.  The operations involved are [quite simple](https://github.com/donmccurdy/glTF-Transform/blob/22ca91764c5122b56d7b0cb57378ca3d3b9f06fe/packages/functions/src/metal-rough.ts#L87-L105).

The conservative conversion uses IOR and Specular (i.e. MeshPhysicalMaterial) but many materials don't actually need those. I'm not sure how to detect the difference automatically, so I tend to think it's good to have a human in the loop and to do the conversion offline where possible.

**Comment by ikeough** [comment]
Thanks @donmccurdy. We've already borrowed the conversion logic from your glTF Transform project and added it to our Elements (.net) library which generates the glTFs.
