### ISSUE TITLE
Crashes on Radeon RX 580 GPU hardware

### ISSUE THREAD

**Issue by Hoodgail** [gkjohnson/three-gpu-pathtracer#323]
I launched https://gkjohnson.github.io/three-gpu-pathtracer/example/bundle/renderVideo.html at that point.
For 30 seconds, the "loading screen" on my computer was frozen.
The tab then turned black, and my display briefly went dark before coming back on.
... all of the WebGL tabs I had open became dark after that, and I then saw this notice.

![image](https://user-images.githubusercontent.com/45743294/206917736-872315a2-47ca-4d47-aaa1-cd92471d53c2.png)

Not sure why, but this happens everytime i open the tab

 - Device: [`Desktop`]
 - OS: [`Windows 11 Version 21H2 (Build 22000.1219)`]
 - GPU: [`Radeon RX 580`]
 - Browser: [`Chrome 108.0.5359.96 (Official Build) (64-bit) (cohort: Stable)`]
 - Three.js version: [r???] (*Which ever the demo is currently using*)
 - Library version: [v???] (*Which ever the demo i currently using*)

**Comment by Hoodgail** [comment]
I also notice that everytime this happens; i start getting 30 fps on every WebGL websites.
But it goes back to normal when i restart my computer

**Comment by Hoodgail** [comment]
![image](https://user-images.githubusercontent.com/45743294/206918157-93f92cd6-d678-4170-bfa6-72c5f24ae9fe.png)

**Comment by gkjohnson** [comment]
This is likely the graphics driver failing on the shader compile or something. Does this happen on the more basic "material ball" demo, as well?

I'm going to assume this is a browser / device issue for now. It's probably best to submit a chrome bug report and see if they can provide more insight into what's happening.

**Comment by Hoodgail** [comment]
Alr, thank you for your response
I'll test the "material ball" demo when i get home to see if it also crashes

**Comment by Hoodgail** [comment]
@gkjohnson 
![image](https://user-images.githubusercontent.com/45743294/207220603-8edcccfd-474d-489a-b3d5-de81a9ecb85f.png)

![image](https://user-images.githubusercontent.com/45743294/207220617-0f45bef7-798a-43a3-804d-e86abaad7d8b.png)

Yup

**Comment by gkjohnson** [comment]
This should be fixed with a workaround from #350, now. Can you give it a try?
