### ISSUE TITLE
All examples crash on Nvidia RTX 2080 Ti

### ISSUE THREAD

**Issue by haroldiedema** [gkjohnson/three-gpu-pathtracer#325]
**Describe the bug**

Any example just renders one frame, or mostly none at all, then freezes the browser for a 5-8 seconds, after which the WebGL context is lost.

**Expected behavior**

It shouldn't crash 😄 

**Screenshots and Repro Model**

The following WebGL error appears in the console. It's similar for all examples.

```
three.module.js:18826 THREE.WebGLProgram: Program Info Log: C:\fakepath(3420,10-36): warning X3577: value cannot be NaN, isnan() may not be necessary.  /Gis may force isnan() to be performed
C:\fakepath(3420,10-36): warning X3577: value cannot be NaN, isnan() may not be necessary.  /Gis may force isnan() to be performed
C:\fakepath(1289,1-6): warning X4000: use of potentially uninitialized variable (dyn_index_vec3_int)
error X8000: D3D11 Internal Compiler Error: Invalid Bytecode: Index Dimension 1 out of range (4263 specified, max allowed is 31) for operand #2 of opcode #4322 (counts are 1-based). Aborting.
error X8000: D3D11 Internal Compiler Error: Invalid Bytecode: Can't continue validation - aborting.

Warning: D3D shader compilation failed with default flags. (ps_5_0)
 Retrying with skip validation
C:\fakepath(3420,10-36): warning X3577: value cannot be NaN, isnan() may not be necessary.  /Gis may force isnan() to be performed
C:\fakepath(3420,10-36): warning X3577: value cannot be NaN, isnan() may not be necessary.  /Gis may force isnan() to be performed
C:\fakepath(1289,1-6): warning X4000: use of potentially uninitialized variable (dyn_index_vec3_int)
error X8000: D3D11 Internal Compiler Error: Invalid Bytecode: Index Dimension 1 out of range (4263 specified, max allowed is 31) for operand #2 of opcode #4322 (counts are 1-based). Aborting.
error X8000: D3D11 Internal Compiler Error: Invalid Bytecode: Can't continue validation - aborting.

Warning: D3D shader compilation failed with skip validation flags. (ps_5_0)
 Retrying with skip optimization
C:\fakepath(3420,10-36): warning X3577: value cannot be NaN, isnan() may not be necessary.  /Gis may force isnan() to be performed
C:\fakepath(3420,10-36): warning X3577: value cannot be NaN, isnan() may not be necessary.  /Gis may force isnan() to be performed
C:\fakepath(3420,10-36): warning X3577: value cannot be NaN, isnan() may not be necessary.  /Gis may force isnan() to be performed
C:\fakepath(3420,10-36): warning X3577: value cannot be NaN, isnan() may not be necessary.  /Gis may force isnan() to be performed
C:\fakepath(1289,1-6): warning X4000: use of potentially uninitialized variable (dyn_index_vec3_int)
C:\fakepath(1933,1): warning X4000: use of potentially uninitialized variable (f_intersectsRectangle)
C:\fakepath(1934,1): warning X4000: use of potentially uninitialized variable (f_intersectsRectangle)
C:\fakepath(1935,1): warning X4000: use of potentially uninitialized variable (f_intersectsRectangle)
C:\fakepath(1951,1): warning X4000: use of potentially uninitialized variable (f_intersectsCircle)
C:\fakepath(1952,1): warning X4000: use of potentially uninitialized variable (f_intersectsCircle)
C:\fakepath(2492,1): warning X4000: use of potentially uninitialized variable (f_envMapDirectionPdf)
C:\fakepath(2032,1): warning X4000: use of potentially uninitialized variable (f_ggxDistribution)
C:\fakepath(2143,1): warning X4000: use of potentially uninitialized variable (f_evalIridescence)
C:\fakepath(2270,1): warning X4000: use of potentially uninitialized variable (f_transmissionEval__SurfaceRec)
C:\fakepath(2032,1): warning X4000: use of potentially uninitialized variable (f_ggxDistribution)
C:\fakepath(1289,1-6): warning X4000: use of potentially uninitialized variable (dyn_index_vec3_int)
C:\fakepath(2032,1): warning X4000: use of potentially uninitialized variable (f_ggxDistribution)
C:\fakepath(2143,1): warning X4000: use of potentially uninitialized variable (f_evalIridescence)
C:\fakepath(2270,1): warning X4000: use of potentially uninitialized variable (f_transmissionEval__SurfaceRec)
C:\fakepath(2032,1): warning X4000: use of potentially uninitialized variable (f_ggxDistribution)
C:\fakepath(2492,1): warning X4000: use of potentially uninitialized variable (f_envMapDirectionPdf)
C:\fakepath(1289,1-6): warning X4000: use of potentially uninitialized variable (dyn_index_vec3_int)
C:\fakepath(2032,1): warning X4000: use of potentially uninitialized variable (f_ggxDistribution)
C:\fakepath(2143,1): warning X4000: use of potentially uninitialized variable (f_evalIridescence)
C:\fakepath(2270,1): warning X4000: use of potentially uninitialized variable (f_transmissionEval__SurfaceRec)
C:\fakepath(2032,1): warning X4000: use of potentially uninitialized variable (f_ggxDistribution)
```

After which (sorry, had to take a screenshot since the browser is unresponsive, so couldn't copy-paste text):

![image](https://user-images.githubusercontent.com/567518/207181380-89a845fd-f9fc-4c75-b175-cfb38a1d6aea.png)

**Platform:**

 - Device: Desktop
 - OS: Windows 11
 - GPU: Nvidia RTX 2080 Ti
 - Browser: Brave [Version 1.46.140 Chromium: 108.0.5359.99 (Official Build) (64-bit)](https://brave.com/latest/)
 - Three.js version: N/A (live examples from this repo)
 - Library version: N/A (live examples from this repo)

**Comment by optimus007** [comment]
can confirm ,same error on gtx1650  , the example on three js runs fine 
all examples after v0.0.7 seems to freeze for a long time then crash with webGL context lost

**Comment by gkjohnson** [comment]
Thanks! Has anyone been able to submit a chrome bug report yet?

**Comment by optimus007** [comment]
Tried on firefox also
three js examples page works on firefox (takes 10-15 sec to render first pathtraced frame just like chrome)
here the console messages 
```
This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”. lego.html
WebGL warning: texSubImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
THREE.WebGLProgram: Program Info Log: C:\fakepath(3817,10-43): warning X3577: value cannot be NaN, isnan() may not be necessary.  /Gis may force isnan() to be performed
C:\fakepath(3817,10-43): warning X3577: value cannot be NaN, isnan() may not be necessary.  /Gis may force isnan() to be performed
error X8000: D3D11 Internal Compiler Error: Invalid Bytecode: Index Dimension 1 out of range (4909 specified, max allowed is 31) for operand #2 of opcode #5090 (counts are 1-based). Aborting.
error X8000: D3D11 Internal Compiler Error: Invalid Bytecode: Can't continue validation - aborting.

Warning: D3D shader compilation failed with default flags. (ps_5_0)
 Retrying with skip validation
C:\fakepath(3817,10-43): warning X3577: value cannot be NaN, isnan() may not be necessary.  /Gis may force isnan() to be performed
C:\fakepath(3817,10-43): warning X3577: value cannot be NaN, isnan() may not be necessary.  /Gis may force isnan() to be performed
error X8000: D3D11 Internal Compiler Error: Invalid Bytecode: Index Dimension 1 out of range (4909 specified, max allowed is 31) for operand #2 of opcode #5090 (counts are 1-based). Aborting.
error X8000: D3D11 Internal Compiler Error: Invalid Bytecode: Can't continue validation - aborting.

Warning: D3D shader compilation failed with skip validation flags. (ps_5_0)
 Retrying with skip optimization
C:\fakepath(3817,10-43): warning X3577: value cannot be NaN, isnan() may not be necessary.  /Gis may force isnan() to be performed
C:\fakepath(3817,10-43): warning X3577: value cannot be NaN, isnan() may not be necessary.  /Gis may force isnan() to be performed
C:\fakepath(3817,10-43): warning X3577: value cannot be NaN, isnan() may not be necessary.  /Gis may force isnan() to be performed
C:\fakepath(3817,10-43): warning X3577: value cannot be NaN, isnan() may not be necessary.  /Gis may force isnan() to be performed
C:\fakepath(2158,1): warning X4000: use of potentially uninitialized variable (f_webgl_c80ce9bbee6f71a0)
C:\fakepath(2159,1): warning X4000: use of potentially uninitialized variable (f_webgl_c80ce9bbee6f71a0)
C:\fakepath(2160,1): warning X4000: use of potentially uninitialized variable (f_webgl_c80ce9bbee6f71a0)
C:\fakepath(2176,1): warning X4000: use of potentially uninitialized variable (f_webgl_7332a1e7afa3679d)
C:\fakepath(2177,1): warning X4000: use of potentially uninitialized variable (f_webgl_7332a1e7afa3679d)
C:\fakepath(2823,1): warning X4000: use of potentially uninitialized variable (f_webgl_2b564ecc20d2ce0b)
C:\fakepath(2270,1): warning X4000: use of potentially uninitialized variable (f_webgl_61a07b44bb90a03c)
C:\fakepath(2381,1): warning X4000: use of potentially uninitialized variable (f_webgl_93b2a4611cd6382b)
C:\fakepath(2521,1): warning X4000: use of potentially uninitialized variable (f_webgl_e2677050a3f5c7d4__webgl_ea73e8e3dfe609bf)
C:\fakepath(2270,1): warning X4000: use of potentially uninitialized variable (f_webgl_61a07b44bb90a03c)
C:\fakepath(2381,1): warning X4000: use of potentially uninitialized variable (f_webgl_93b2a4611cd6382b)
C:\fakepath(2521,1): warning X4000: use of potentially uninitialized variable (f_webgl_e2677050a3f5c7d4__webgl_ea73e8e3dfe609bf)
C:\fakepath(2270,1): warning X4000: use of potentially uninitialized variable (f_webgl_61a07b44bb90a03c)
C:\fakepath(2823,1): warning X4000: use of potentially uninitialized variable (f_webgl_2b564ecc20d2ce0b)
C:\fakepath(2270,1): warning X4000: use of potentially uninitialized variable (f_webgl_61a07b44bb90a03c)
C:\fakepath(2381,1): warning X4000: use of potentially uninitialized variable (f_webgl_93b2a4611cd6382b)
C:\fakepath(2521,1): warning X4000: use of potentially uninitialized variable (f_webgl_e2677050a3f5c7d4__webgl_ea73e8e3dfe609bf)
C:\fakepath(2270,1): warning X4000: use of potentially uninitialized variable (f_webgl_61a07b44bb90a03c) three.module.js:18992:11
WebGL warning: <Present>: Swap chain surface creation failed.
WebGL context was lost.
THREE.WebGLRenderer: Context Lost. three.module.js:27481:10
Failed to create WebGL context: WebGL creation failed: 
* tryANGLE (FEATURE_FAILURE_EGL_POT)
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)
THREE.WebGLRenderer: A WebGL context could not be created. Reason:  WebGL creation failed: 
* tryANGLE (FEATURE_FAILURE_EGL_POT)
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS) three.module.js:27511:10

```

**Comment by gkjohnson** [comment]
They are both likely using the same ANGLE backend. I would appreciate it if someone can report it to chrome or some browser vendor so they can provide more insight on what good next steps are.

**Comment by optimus007** [comment]
reported in chrome (no feedback) and in [bugs.chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1404661) 
reply there with any additional context if required as I'm not familiar with this topic

**Comment by gkjohnson** [comment]
This should be fixed with a workaround from https://github.com/gkjohnson/three-gpu-pathtracer/pull/350, now. Can you give it a try?

**Comment by optimus007** [comment]
Yes it's running! , one warning (screenshot) and it takes a good 20-30 seconds before the first path trace render frame is visible (just like v0.0.7)
![yesss](https://user-images.githubusercontent.com/6885294/211130654-693b8228-556e-43db-8d62-b49dd8c765e7.png)

**Comment by gkjohnson** [comment]
@optimus007 Great, thanks!

> It takes a good 20-30 seconds before the first path trace render frame is visible (just like v0.0.7), then it's smooth

The 20-30 second delay is concerning. I'm wondering if it's due to the ANGLE shader conversion. @kenrussell any thoughts here? It takes significantly longer on windows that it does on my mac laptop, for example.

**Comment by haroldiedema** [comment]
I can confirm the workaround has fixed the issue. Like @optimus007 said, it takes about 20-30 seconds for the initial render. After which, it runs smoothly.

**Comment by kenrussell** [comment]
ANGLE invokes Microsoft's fxc shader compiler to compile the HLSL generated by ANGLE's shader translator, which ingests GLSL. I suspect the huge slowdown is in fxc, which has known pathologies in shader compilation time in some situations.

A "Javascript and rendering" type trace from `about:tracing` in Chrome would indicate more clearly whether the time's spent in ANGLE or in fxc.

Can you extract the path tracer's shaders into separate text files, ideally with the translated HLSL gathered from the `WEBGL_debug_shaders` extension? We can also try invoking fxc from the command line to see if it's taking a long time on certain shaders.

**Comment by haroldiedema** [comment]
Sure thing, here's a trace with just `gpu.angle` enabled.

[trace_gpu-angle.json.gz](https://github.com/gkjohnson/three-gpu-pathtracer/files/10371401/trace_gpu-angle.json.gz)

I think @gkjohnson should have a look at your second question. I'm not that familiar with this codebase 😅

**Comment by gkjohnson** [comment]
Sorry to ping @kenrussell - any further thoughts here? It would be great to find some way to get the shaders compiling faster on windows. Right now the delay and browser lock is fairly debilitating.

**Comment by gkjohnson** [comment]
I took some timing on my Windows 10 (Intel i7-7700k 4.20Ghz, RTX 2070 Super) machine with both the default D3D11 ANGLE backend and the OpenGL backend by changing the `chrome://flags#use-angle` flag. These are the times it takes to run three.js' `renderer.compile` on a mesh with the path tracing shader. The shader was modified by adding an unused function between page refreshes to avoid cached shader usage after refresh. I suppose it might be expected but you can see nearly an order of magnitude improvement using the OpenGL backend compared to the default and it feels much better to use.

| | D3D11 | OpenGL |
|---|---|---|
| run 1 | 19834.85ms | 2690.06ms |
| run 2 | 20656.49ms | 2636.80ms |
| run 3 | 22511.31ms | 2662.25ms |
| run 4 | 19712.05ms | 2664.36ms |
| average | 20678.67ms | 2663.37ms |
| cached refresh | ~600ms | ~60ms |

Looking at the write up for the flag:

> Choose the graphics backend for ANGLE. D3D11 is used on most Windows computers by default. Using the OpenGL driver as the graphics backend may result in higher performance in some graphics-heavy applications, particularly on NVIDIA GPUs. ***It can increase battery and memory usage of video playback.*** – Windows

It would be nice to know how severely the the OpenGL backend can bloat memory and battery usage and whether it's improved over the years.

**Comment by aile1997** [comment]
After opening this example, my rtx browser will crash for a while, and each rendering needs to wait more than ten seconds, and there will be very messy noise after rotating the view, can it be improved to real-time ray tracing?

**Comment by gkjohnson** [comment]
> After opening this example, my rtx browser will crash for a while, and each rendering needs to wait more than ten seconds

This is explained in the thread.

> there will be very messy noise after rotating the view, can it be improved to real-time ray tracing

The project is targeting high fidelity path tracing rather than real time rendering - feel free to recommend or provide improvements to faster convergence.

**Comment by gkjohnson** [comment]
The original issue is addressed - and the compilation delay is due to an already-reported Chrome issue so I'm going to close this for the moment.

**Comment by Wizer21** [comment]
Hello !
This warning seem's to be back :(

For me it appear rarely on chrome and edge.
I got the following warning the first time I opened “Camera Depth of Field” on edge, and it didn't reappear.<img src="https://github.com/user-attachments/assets/7f9b2554-5b74-4446-9176-e0f3c3d38ae90" width="400">

On Firefox I got the warning systematically on the 5 examples I tried.

Graphic card NVIDIA GeForce RTX 3070 Ti Laptop GPU
Processor 12th Gen Intel(R) Core(TM) i9-12900H 2.50 GHz
Chrome 128.0.6613.85 
Edge 127.0.2651.105
Firefox 129.0.2

**Comment by gkjohnson** [comment]
Can you make a new issue with more details and check if previous versions work in the browser? These are the kinds of things that can break between browser updates. Windows has been particularly problematic.
