### ISSUE TITLE
Subsurface scattering support 🤔

### ISSUE THREAD

**Issue by Shrilliant** [gkjohnson/three-gpu-pathtracer#353]
**Is your feature request related to a problem? Please describe.**

I looked at the [material database](https://gkjohnson.github.io/three-gpu-pathtracer/example/bundle/materialDatabase.html) and realized that skin is listed, so I checked the demo and the skin materials don't render subsurface scattering, which is an important part of creating [realistic skin in three.js](https://www.derschmale.com/lab/doodles/skinsss/build/) in a raytracer. 

I have a couple projects that also could benefit from an implementation of [subsurface scattering](https://en.wikipedia.org/wiki/Subsurface_scattering), mainly a face generator that I'm working on. Supporting something like this could make the this webgl renderer stand out, since I spent a few hours looking and I haven't managed to find a single one that supports this using webgl (◞‸◟；)

**Describe the solution you'd like**

I looked into solving the problem and I quickly realized that I wouldn't know how to do it, but I think [this](https://gamedev.stackexchange.com/questions/32833/what-is-an-easy-way-to-work-subsurface-scattering-into-a-raycaster?rq=1) may be a helpful starting point (maybe) if you do decide to try to implement the feature 🥺

**Comment by gkjohnson** [comment]
SSS would be great! So far it's not defined in glTF or three.js, though. But at some point I'd like to add it - definitely open to contributions. I'll merge issue this in with #271 for the time being.
