### ISSUE TITLE
Switching bundler to `vite` instead of `parcel` breaks web workers

### ISSUE THREAD

**Issue by hybridherbst** [gkjohnson/three-gpu-pathtracer#355]
**Describe the bug**

I've seen the [remarks that different bundlers may require different syntax for workers](https://github.com/gkjohnson/three-gpu-pathtracer#asynchronous-scene-generation), but I'm a bit stumped as to what that means in practice, and can't get it to work. 

The following steps switch to vite as bundler:

- run `npm install --save-dev vite`
- in package.json, add `"start-vite": "cd example && vite --host",` in `scripts`
- run `npm run start-vite`
- visit the page
- note loading works fine, then the MeshBVH worker returns undefined and logs to the console: `Uncaught (in promise) Error: GenerateMeshBVHWorker: undefined`

**Expected behavior**

Switching to another bundler works, it's often required to integrate three-gpu-pathtracer / three-mesh-bvh into other projects. I understand there may need to be changes but it's unclear to me what those changes would be.

From what I understand, the syntax in both _three-gpu-pathtracer_ and _three-mesh-bvh_ should already match what's described here:  
https://vitejs.dev/guide/features.html#web-workers

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome]

**Comment by gkjohnson** [comment]
> "start-vite": "cd example && vite --host"

I'm not a vite expert but cd-ing into examples away from the root where node_modules etc are installed seems like it could be a problem. Is it possible to run vite in the root and load the examples pages?

**Comment by hybridherbst** [comment]
I don't think that matters – just tried

- switch to `"start-vite": "vite --host",`
- run `npm run start-vite`
- open `http://localhost:5173/example/index.html`

The result is unfortunately identical:  
![image](https://user-images.githubusercontent.com/2693840/211312544-161a5e7e-ef9e-4ecc-99b9-04ba05048738.png)

**Comment by gkjohnson** [comment]
cc @drcmda - any thoughts here?

**Comment by gkjohnson** [comment]
@hybridherbst this might be something to ask the vite project about. From what I can see the three-mesh-bvh is importing workers in the format that vite requires.

**Comment by hybridherbst** [comment]
I agree, looks correct. Opened an issue with vite (https://github.com/vitejs/vite/issues/11672)

**Comment by gkjohnson** [comment]
Sounds like this is confirmed to be a vite issue - I'll close the issue here for now.
