### ISSUE TITLE
Can switch normal scene <-> path traced scene?

### ISSUE THREAD

**Issue by dongho-shin** [gkjohnson/three-gpu-pathtracer#359]
I try my question but something weird
canvas1 -> A WebGLRenderer
canvas2 -> B WebGLRenderer with cloned scene of canvas1
A & B WebGLRenderer is different instance and has own canvas element

first time of canvas1 -> 2 goes good also 2->1(because 2 -> just switch canvas 2 to 1 and reset & dispose about pathtracer
and then canvas 2 -> 1's do looks weird. number of Samples go up but nearly enhance it's quality

**Comment by gkjohnson** [comment]
Sorry it's not clear what issue you're running in to. Can you make a live example like a JSFiddle showing the problem?
