### ISSUE TITLE
How to set background as white？

### ISSUE THREAD

**Issue by kiwenlau** [gkjohnson/three-gpu-pathtracer#372]
For [Physically Based Materials](https://gkjohnson.github.io/three-gpu-pathtracer/example/bundle/index.html), I changed bgGradientTop and bgGradientBottom as ffffff, but the background is gray instead of white：

<img width="1920" alt="white" src="https://user-images.githubusercontent.com/10240841/215725425-c424f902-a84c-4536-a50c-66cba1722fb2.png">

How to set background as white？

If I understand right, the color is interpolate between bgGradientTop and bgGradientBottom, I tried to change the source code of [GradientEquirectTexture](https://github.com/gkjohnson/three-gpu-pathtracer/blob/1962d731d292cb769570adbc5997c17746c2dce0/src/textures/GradientEquirectTexture.js), but it is not working：

```javascript
color.lerpColors( 0xffffff, 0xffffff, 0 );
```

<img width="574" alt="code" src="https://user-images.githubusercontent.com/10240841/215742705-5393dbd1-dfc6-4c96-aa84-278553f94b9e.png">

**Comment by gkjohnson** [comment]
If you'd like to use exact CSS colors (ie 0xffffff being displayed as white) then you need to disable tone mapping (see the "acesToneMapping" toggle)
