### ISSUE TITLE
browser freeze after model loaded

### ISSUE THREAD

**Issue by x1911** [gkjohnson/three-gpu-pathtracer#390]
**Describe the bug**

the browser freeze after model loaded

**Screenshots and Repro Model**

<img width="942" alt="image" src="https://user-images.githubusercontent.com/8219031/218926747-274f5be9-eda3-4e58-8d2a-0a9b87b9afb7.png">

**Platform:**

 - Device:Desktop
 - OS: Windows, MacOS
 - GPU: NVidia and Intel Iris 
 - Browser:  Chrome and Safari
 - Three.js version: [r147]
 - Library version: [v0.0.13]

**Comment by gkjohnson** [comment]
Please put some more effort into your report... If you want to help you have to provide hardware model information, os version information, expand the logs, browser versions...

**Comment by x1911** [comment]
MacBook Pro Retina, 15-inch
2.2G i7  16G
Intel Iris pro
mac monterey 12.6.2
chrome 107.0.5304.87

**Comment by gkjohnson** [comment]
It sounds like this machine is 10 years old. I don't expect Apple or browser vendors to provide updates to improve support for graphics drivers in this case so it's likely this project will not be able to run on such a machine in this case.

**Comment by x1911** [comment]
What a pity
https://gkjohnson.github.io/three-mesh-bvh/example/bundle/gpuPathTracingSimple.html
https://gkjohnson.github.io/three-mesh-bvh/example/bundle/gpuPathTracing.html

It still works with this two examples

**Comment by gkjohnson** [comment]
> It still works with this two examples

Yes - there are many things that can cause a platform to break when it comes to shader complexity. Tracking down and fixing where one platform doesn't follow spec correctly is brittle and potentially makes other platforms more difficult to maintain. It's made more difficult if there are not clear errors especially on such an old machine.
