### ISSUE TITLE
WebGPU support

### ISSUE THREAD

**Issue by georgy95** [gkjohnson/three-gpu-pathtracer#431]
Chrome team is shipping WebGPU support in 113 release. 

I'm curious to find out about your plans on WebGPU and if this release has any significant impact on the project. Is [three-gpu-pathtracer](https://github.com/gkjohnson/three-gpu-pathtracer) compatible with the `WebGPURenderer` as is?

Three.js currently has limited support for `WebGPURenderer`.

**Comment by gkjohnson** [comment]
Hello! WebGPU is still very new and while I haven't used it yet I'm not sure if the three.js WebGPURenderer is considered stable. Once the ecosystem has matured a bit more an upgrade to WebGPU would be good for the project - I'm hoping it should provide some improvements especially with the ability to move rendering into a computer shader.

If you're interested in contributing some work or experimenting on this it would be greatly appreciated. The raycasting logic in [three-mesh-bvh](https://github.com/gkjohnson/three-mesh-bvh/) would be the place to start.
