### ISSUE TITLE
is there any way to set envMap with different background?

### ISSUE THREAD

**Issue by dongho-shin** [gkjohnson/three-gpu-pathtracer#434]
![untitled 192_1](https://user-images.githubusercontent.com/108255990/233515031-6b07e5bc-185c-454a-b69a-17815418314d.png)
Hi is there any way to set envMap with different background?
like this image from keyshot

More details
```
scene.background = new THREE.Color(0xff00ff)
scene.environment = await new RGBELoader().loadAsync('DownloadHDRI URL')
```

if it can't why?
Is it because a PathTracing light can update pixels in a texture?

**Comment by gkjohnson** [comment]
Multiple of the examples set both the background map and the lighting environment map to different textures. If you look [here](https://github.com/gkjohnson/three-gpu-pathtracer#physicalpathtracingmaterial) in the docs you can see separate `backgroundMap` and `envMapInfo` fields to set separately. Is this what you're referring to?

**Comment by dongho-shin** [comment]
@gkjohnson Yepp Thanks!! but it looks like converting normal Image(jpeg, png) to like HDRI
I want to set background via THREE.Color, THREE.Texture(not HDRI), THREE.DataTexture(HDRI I check it works)

**Comment by dongho-shin** [comment]
@gkjohnson Oh Thanks I get it
I mean I test a Texture from png below
![KakaoTalk_Image_2023-04-03-18-37-57](https://user-images.githubusercontent.com/108255990/234436428-2f262869-e564-4e24-b0f5-5a8b9d367f6c.jpeg)

Result
https://user-images.githubusercontent.com/108255990/234436357-6d8e92be-4a4a-4a79-a86b-ff5cc1c49305.mov

so I think PathTrace Shader convert Texture to equirectangular Map

P.S : BTW I confused the word sorry I just focus visual effects, so I use HDRI and Equirectangular Map interchangeably
Also I always  appreciate your kind reply. Have a good day
