### ISSUE TITLE
Add DirectionalLight and PointLight to DynamicPathTracingSceneGenerator

### ISSUE THREAD

**Issue by relujoa** [gkjohnson/three-gpu-pathtracer#437]
I'm using DynamicPathTracingSceneGenerator.
And I added a DirectionalLight to group.
```
const group = new THREE.Group();
group.add(new THREE.DirectionalLight(0xffffff, 1));
const generator = new DynamicPathTracingSceneGenerator(group);
const result = generator.generate();
const { bvh, textures, materials, lights } = result;
```
But, I couldn't get any DirectionalLight object from the code.

In the index.umd.cjs file, I found generate() code from DynamicPathTracingSceneGenerator.
```
for ( let i = 0, l = objects.length; i < l; i ++ ) {
    objects[ i ].traverse( c => {
        if ( c.isMesh ) {
            const normalMapRequired = ! ! c.material.normalMap;
            setCommonAttributes( c.geometry, { attributes, normalMapRequired } );
        } else if ( c.isRectAreaLight || c.isSpotLight ) {
            this.lights.push( c );
        }
} );
```
Why this code is ```if(c.isRectAreaLight || c.isSpotLight)```?
I think this should be ```if(c.isRectAreaLight || c.isSpotLight || c.isDirectionalLight || c.isPointLight )```

**Comment by gkjohnson** [comment]
Hello! Thanks for the catch. Would you like to make a PR with a fix?

**Comment by relujoa** [comment]
> Hello! Thanks for the catch. Would you like to make a PR with a fix?
yes, please.

**Comment by relujoa** [comment]
yes, please.
