### ISSUE TITLE
Safari compatibility on Mac & iOS

### ISSUE THREAD

**Issue by ChazHollywood** [gkjohnson/three-gpu-pathtracer#439]
I haven't been able to get the pathtracer to work at all in Safari on Mac or iOS, both updated to the latest versions as of today. Everything works fine on Chrome. The problem occurs whether I'm using the Github hosted demos or from a local server. 

One clue is the black "Loading" page does appear, however it fails just before the loading percentage begins.

This problem does not occur with the "skinned geometry support" or "morph target support" demo's. All other demos cause the error: 

A problem repeatedly occurred with "https://gkjohnson.github.io/three-gpu-pathtracer/example/bundle/basic.html"
[Reload Webpage]

Because of the nature of the error it results in no page loading into the tab and therefore no way that I know of to look for errors.

Mac is a MacBook Pro 16" M1 and the phone is a 14 Pro.

<img width="541" alt="Screenshot 2023-06-05 at 8 42 34 AM" src="https://github.com/gkjohnson/three-gpu-pathtracer/assets/135338745/355c3749-3050-48ef-835d-1203bd17d4ec">

**Comment by gkjohnson** [comment]
See https://github.com/gkjohnson/three-gpu-pathtracer/issues/441#issuecomment-1610640494

**Comment by gkjohnson** [comment]
Fixed in #483
