### ISSUE TITLE
Android Shader compilation error

### ISSUE THREAD

**Issue by NickMundel** [gkjohnson/three-gpu-pathtracer#442]
**Describe the bug**
When trying to view the webpage on my android device, an error occurs and rendering is halted. This results in a blank page.

A clear and concise description of what the bug is. Before submitting, please remove unnecessary sections.

**Expected behavior**

Well I used the basic example as a template and haven't changed it.

**Screenshots and Repro Model**
![Screenshot 2023-06-08 214025](https://github.com/gkjohnson/three-gpu-pathtracer/assets/64857616/19c62aba-b355-49e1-86a8-0b78008a9346)

**Platform:**

 - Device: Mobile
 - OS: Android 13
 - GPU: Qualcomm Snapdragon 778G 5G (SM7325)
 - Browser: Chrome 114.0.5735.57, FireFox 113.2.0
 - Three.js version: 0.153.0
 - Library version: 0.0.15

**Comment by gkjohnson** [comment]
See https://github.com/gkjohnson/three-gpu-pathtracer/issues/441#issuecomment-1610640494

**Comment by gkjohnson** [comment]
Fixed in #483 by upgrading three-mesh-bvh version
