### ISSUE TITLE
Path Tracing not working properly on rendering a different GLTF model

### ISSUE THREAD

**Issue by PalashGarg19** [gkjohnson/three-gpu-pathtracer#444]
I am trying to path trace my gltf model by modifying url in _**index.js**_ file. When I disable the path tracing everything seems to be working perfectly but when I enable it I can see some dark triangles in my scene(which shouldn't be the case). Feels like some meshes are also being scrapped off. Am i missing something or is there an issue. I am attachig the screenshots for your reference. Thanks in advance!!
![without_path_tracing](https://github.com/gkjohnson/three-gpu-pathtracer/assets/108533092/ddc644cc-f0aa-4d08-b087-0db46d79a8f1)
![with_path_tracing](https://github.com/gkjohnson/three-gpu-pathtracer/assets/108533092/57cb9176-4c74-4a63-970d-0fd833a514b1)

**Comment by PalashGarg19** [comment]
@ChazHollywood Yes I was using Chrome.
And yes on firefox it is rendering correct. Do you know the what's the issue in Chrome?

**Comment by ChazHollywood** [comment]
> @ChazHollywood Yes I was using Chrome.
> And yes on firefox it is rendering correct. Do you know the what's the issue in Chrome?

I don't know other than it was working in Chrome prior to the latest Chrome update. I happen to be on a Mac. Are you on Mac or PC? Can reply to my issue 441 saying you're having the same problem? Thank you.

**Comment by PalashGarg19** [comment]
@ChazHollywood I am on linux actually(Ubuntu 22.04).

**Comment by gkjohnson** [comment]
See https://github.com/gkjohnson/three-gpu-pathtracer/issues/441#issuecomment-1610640494

**Comment by gkjohnson** [comment]
With the latest published version of three-mesh-bvh this should be addressed. (see https://github.com/gkjohnson/three-gpu-pathtracer/issues/441#issuecomment-1711198498)

If there's still an issue we can reopen.
