### ISSUE TITLE
Handle meshes with negative scale

### ISSUE THREAD

**Issue by JerryI** [gkjohnson/three-gpu-pathtracer#446]
I am not sure if it connected with Path rendering engine or with three.js. So...

Matrix transformation applied on a scene (or any of its group) does not show any effect. However, when method `updateMatrixWorld` is applied on a scene, the color and textures disappears but the transformation finally happens.

## step 1
Apply matrix transformation

```js
  group.applyMatrix4(new THREE.Matrix4().set(
    1, 0, 0, 0,
    0, 0, 1, 0,
    0, 1, 0, 0,
    0, 0, 0, 1));

  scene.add(group);
  
  //initialization of a render
  const generator = new RTX.DynamicPathTracingSceneGenerator( scene );
  const sceneInfo = generator.generate( scene );
  const { bvh, textures, materials } = sceneInfo;

  const geometry = bvh.geometry;
  const material = ptRenderer.material;

  material.bvh.updateFrom( bvh );
  material.attributesArray.updateFrom(
    geometry.attributes.normal,
    geometry.attributes.tangent,
    geometry.attributes.uv,
    geometry.attributes.color,
  );

  material.materialIndexAttribute.updateFrom( geometry.attributes.materialIndex );
  material.textures.setTextures( renderer, 2048, 2048, textures );
  material.materials.updateFrom( materials, textures );
...
```

Result geometrically is __wrong__. Applied matrix has no effect

![image](https://github.com/gkjohnson/three-gpu-pathtracer/assets/4111822/cc9f3e7f-7d0a-400d-b9d8-82d73451fc5a)

## step 2
adding update method

```js
  group.applyMatrix4(new THREE.Matrix4().set(
    1, 0, 0, 0,
    0, 0, 1, 0,
    0, 1, 0, 0,
    0, 0, 0, 1));

  scene.add(group);

  //added here!
  scene.updateMatrixWorld();
  
  //initialization of a render
```

Result geometrically is correct, but has no textures or colors

![image](https://github.com/gkjohnson/three-gpu-pathtracer/assets/4111822/0fa17cfe-3f37-4ab4-aa6c-ffc354336221)

**Platform:**

 - Device: [Desktop]
 - OS: [Linux]
 - GPU: [NVidia 1660]
 - Browser: [Firefox]
 - Three.js version: [r143]
 - Library version: [latest]

**Comment by gkjohnson** [comment]
> that the renderer falls back to three.js engine

This isn't the case. The matrix you're applying represents a negative scale which inverts the geometry so back faces are facing outwards:

> new THREE.Matrix4().set(
>    1, 0, 0, 0,
>    0, 0, 1, 0,
>    0, 1, 0, 0,
>    0, 0, 0, 1 ).determinant() === - 1

The pathtracer doesn't handle this at the moment - you'll have to apply a transform matrix with a positive scale.

**Comment by JerryI** [comment]
@gkjohnson , oh thank you a lot. This was so so easy to fix.
Now it looks great. A tried a couple of example from my project. Those shadows, lighting mmm. fantastic
![Screenshot from 2023-07-19 16-27-01](https://github.com/gkjohnson/three-gpu-pathtracer/assets/4111822/f13829be-42c3-4ef5-919a-3e7eb1471f69)
