### ISSUE TITLE
Black dots appear in 0.0.15

### ISSUE THREAD

**Issue by nine-fox** [gkjohnson/three-gpu-pathtracer#447]
**Describe the bug**

I used the same configuration for the rendering, except the three-gpu-pathtracer version is different. Please take a look at the image 0.0.15. There are lots of black dots there, compared with 0.0.14 and 0.0.7

**Expected behavior**

No black dots

**Screenshots and Repro Model**

![1](https://github.com/gkjohnson/three-gpu-pathtracer/assets/27168281/f490f07d-9c23-4087-9562-7a54b1c0572f)
![2](https://github.com/gkjohnson/three-gpu-pathtracer/assets/27168281/4dc89c90-ce17-4a3b-be8e-582651ca512e)
![3](https://github.com/gkjohnson/three-gpu-pathtracer/assets/27168281/65197ed5-e3ab-42ac-8906-737a96222578)

**Platform:**

 - Device: Thinkpad Nano X1
 - OS: Windows
 - GPU: Onboard
 - Browser: latest Edge
 - Three.js version: r154
 - Library version: 0.0.15

**Comment by gkjohnson** [comment]
Please provide a model that can be used for a reproduction of the issue.

**Comment by nine-fox** [comment]
> Nice renders! Can you please provide a model that can be used for a reproduction of the issue?

Hi thanks for your reply. Please see the following. The env map is: Drachenfels Cellar

[nine-fox-glb.zip](https://github.com/gkjohnson/three-gpu-pathtracer/files/12080169/nine-fox-glb.zip)

**Comment by nine-fox** [comment]
> Thanks - I'll take a look when I get a chance. If you have the availability to run a git bisect to determine which commit or at least which PR caused this issue that would be helpful.

After some investigations, I found the following commit may be related:

![aaa](https://github.com/gkjohnson/three-gpu-pathtracer/assets/27168281/c6230a0b-94ed-4459-bd63-2d9941c2cc64)

I am not an expert for this, so may leave it to you to dig :-)

**Comment by nine-fox** [comment]
> Thanks - looks like PR #428 caused the problem. PR #448 reverts the commit - do you mind testing it to see if that addresses the issue?

Thanks for your fix! Not sure how to get that PR. Since there are only several lines changed, I updated my file manually. It looks that the fix works!

Without that fix, I can see the black dot appear.

The image with that fix looks like:

![nine-fox-capture-1515x1093 (13)](https://github.com/gkjohnson/three-gpu-pathtracer/assets/27168281/52a12d70-01ab-4e01-82c3-f7ffd650ce2d)

**Comment by gkjohnson** [comment]
Great - thanks for checking. I'll merge and get a new version published soon.

**Comment by gkjohnson** [comment]
Published!
