### ISSUE TITLE
Broke on MacOS Sonoma: Chrome + Safari

### ISSUE THREAD

**Issue by bhouston** [gkjohnson/three-gpu-pathtracer#450]
**Describe the bug**

I am testing with this URL: https://gkjohnson.github.io/three-gpu-pathtracer/example/bundle/index.html

There is now a very long pause after the WebgL displays because it tries to show the ray traced image.  This occurs on all machines, but on MacOS M1 and M2 devices both Safari and Chrome crash hard.

When trying to rendering, it just crashes with a ContextLost on Safari, screenshot here:
<img width="1279" alt="Screenshot 2023-09-06 at 6 48 56 AM" src="https://github.com/gkjohnson/three-gpu-pathtracer/assets/588541/3b360148-7d46-48ad-a6fd-0dce5eb9ec90">

On Chrome it goes white when it crashes - takes about 30s after it finishes loading before it crashes hard:

<img width="1595" alt="Screenshot 2023-09-06 at 6 51 11 AM" src="https://github.com/gkjohnson/three-gpu-pathtracer/assets/588541/e69d5e59-6e48-4c42-b738-08ae983b8af6">

LGL Tracer works on hthese machines fine .

I am running the betas of MacOS Senoma - this is an advanced beta and maybe what is eventually released.  I believe it also crashes on other versions of MacOS as well, but I haven't been able to confirm.

**Expected behavior**

It should work and there should be no pauses during loading.

**Screenshots and Repro Model**

Just the base renderer with default models crashes.

**Platform:**

 - Device: Desktop MasOC
 - OS: MacOS
 - GPU: M1 and M2
 - Browser: Chrome + Safari
 - Three.js version: whatever is currently live on the website.
 - Library version: whatever is currently live on the website.

**Comment by bhouston** [comment]
I was able to work around the bug on Safari and Chrome - I just had to disable MIS.  Then it works.  So something in the MIS code is causing the crash.

**Comment by gkjohnson** [comment]
Also possibly related to #450, #439

**Comment by JerryI** [comment]
I also tried M1 (Air, Sonoma)
- Chrome (Electron) just crash
- Firefox infinite loading
- Safari freezes and crashes

Hope someone will find the solution. M1 is quite powerful, could be great to utilize it

**Comment by gkjohnson** [comment]
Fixed in #483!
