### ISSUE TITLE
Could you show a basic example such as a sphere?

### ISSUE THREAD

**Issue by jiywang3** [gkjohnson/three-gpu-pathtracer#453]
I am trying to use your library in a regular THREE.js project by following the example at https://github.com/gkjohnson/three-gpu-pathtracer/blob/main/example/basic.js. But I got lost with the texture mapping. Could you show a basic example such as a sphere?

**Comment by gkjohnson** [comment]
Here's a fairly basic example. It's still a bit long that maybe that can be addressed in future releases:

https://jsfiddle.net/c2asgdqu/3/

<img width="703" alt="image" src="https://github.com/gkjohnson/three-gpu-pathtracer/assets/734200/7e8683ab-1f11-4344-9468-6631d5a16a2d">
