### ISSUE TITLE
Can't see the examples.

### ISSUE THREAD

**Issue by oh-jinsu** [gkjohnson/three-gpu-pathtracer#456]
Hello, want to check out the examples, the shader errors occur.

I wonder the reason of those errors.

<img width="1551" alt="Screenshot 2023-10-06 at 3 40 56 PM" src="https://github.com/gkjohnson/three-gpu-pathtracer/assets/101033584/5f3df0cc-7d05-470a-97d0-ff6030cab356">

**Platform:**

 - Device: M1 Mac
 - OS: Ventura 13.3.1
 - GPU: [NVidia ??, Radeon ??, ...]
 - Browser: Chrome
 - Three.js version: 0.157.0
 - Library version: 0.0.16

**Comment by gkjohnson** [comment]
Can you please provide the Chrome browser version and more details on your hardware from "About This Mac" (chip, memory, size, year, etc). I've noticed the demos seem to work on some M1 hardware but not others even from the same year. Unfortunately this is not a simple issue to track down.

**Comment by oh-jinsu** [comment]
Yes, It doesn't seem simple to track down. I want to help fixing if there's any clue though.

Chrome browser is up-to-date: Version 117.0.5938.149 (Official Build) (arm64)
But I also checked it does not work on Safari.

![Screenshot 2023-10-06 at 4 09 49 PM](https://github.com/gkjohnson/three-gpu-pathtracer/assets/101033584/b20aadb6-5e9a-4102-84d5-16f2b4bbcd2b)

Mac: MacBook Pro 13, M1, 16GB RAM, 500GB, 2020, Ventura 13.3.1

**Comment by gkjohnson** [comment]
> Yes, It doesn't seem simple to track down. I want to help fixing if there's any clue though.

My only assumption is that it's crashing on shader compilation - though the lack of meaningful errors doesn't help with that. On my 2021 M1 Macbook Pro 14-inch, 32 GB, Ventura 13.5 machine it works in Chrome but not in Safari.

It's unclear if the compile just stalls too long, the driver or compiler caps the memory for the shader, or there's an idiosyncrasy on different machines for specific syntax, function calls, shader structure, etc. The only way I know of to debug this is to remove lots of code in path tracing shader (comment it out) and then slowly add functionality back in until it breaks. And then narrow down the specific issue in a binary-search-type approach. It's a bit tedious but it's worked for me before. If you have interest in helping to dig into this I'd of course appreciate the help.

**Comment by robertoranon** [comment]
I had the same problem, and "solved" it by disabling MIS, e.g. with

`material.setDefine( 'FEATURE_MIS', 0 );`

on the material that is created after loading the gltf model

**Comment by oh-jinsu** [comment]
Thank you. Disabling 'FEATURE_MIS' solves the probem.

And I figured out when 'FEATURE_MIS' is enabled, 'main' function in the fragment shader calls 'directLightContribution()'. This function leads to calling 'traceScene()' and passing 'lights' paramter to it causes the problem. Still I have no idea with the reason.

So I suggested replacing the paramter with the global uniform 'lights' if no problem expected.

Details:
https://github.com/gkjohnson/three-gpu-pathtracer/pull/457

**Comment by gkjohnson** [comment]
Yes disabling MIS fixes the issue but I expect only because uses a code path that is significantly less complex and therefore less likely to hit some of these weird compile bugs.

> calling 'traceScene()' and passing 'lights' paramter to it causes the problem. Still I have no idea with the reason.
> ...
> Details:
> https://github.com/gkjohnson/three-gpu-pathtracer/pull/457

Thanks for the PR - I'll be taking a deeper look at this when I get the chance. Probably this weekend. I'm hoping there's a more satisfying explanation for the issue but I'm not hopeful.
