### ISSUE TITLE
problem with loading a glb/gltf file

### ISSUE THREAD

**Issue by adityakailash0399** [gkjohnson/three-gpu-pathtracer#458]
**Describe the bug**
While passing a glb file to the three-gpu-path tracer the mesh looks wierd

**Expected behavior**

It should load fine
**Screenshots and Repro Model**

Model Link - https://github.com/adityakailash0399/model/blob/main/omega_watch_v02.glb 

<img width="957" alt="Screenshot 2023-09-27 at 8 04 33 PM" src="https://github.com/gkjohnson/three-gpu-pathtracer/assets/128450417/481c21d2-7db7-458d-9409-8f66579d9a28">

Please check the screenshot
**Platform:**

 - Device: [Desktop]
 - OS: [MacOS]
 - GPU: [M1]
 - Browser: [Chrome]
 - Browser Version: [116.0.5845.187 (Official Build) (arm64)]
 - Three.js version: [r0.152.0]
 - Library version: [v^0.6.3]

**Comment by gkjohnson** [comment]
If you just ignore the issue template the requests for a model to test and system specs then I can't help you.

**Comment by adityakailash0399** [comment]
Hey @gkjohnson ,I have added the necessary details. Please check

**Comment by gkjohnson** [comment]
Again, please provide the model. Nothing can be investigated with just a screenshot. 

> Library version: [v0.152.0]

And there is no version 0.152.0 of this library. Please provide the version of this project you're using.

**Comment by adityakailash0399** [comment]
I have provided the link to the model. Plus I have updated the library version as well

**Comment by gkjohnson** [comment]
I am unable to reproduce the issue on my machine - this may be a browser / device issue but please make sure you're on the latest version of the project. You _still_ have not provided the version of the library you are using. There is no v0.6.3 of _three-gpu_pathtracer_. Please provide the version for ***three-gpu-pathtracer***.

If v0.6.3 is the version of three-mesh-bvh you are using then that is out of date, as well. Make sure you are using the latest versions of your packages.

<img width="644" alt="image" src="https://github.com/gkjohnson/three-gpu-pathtracer/assets/734200/7bebfaae-d87f-46d5-8a94-58ccb8a11bb6">

**Comment by adityakailash0399** [comment]
@gkjohnson , tried rendering on the Windows machine, this worked fine. Can I say is it an issue on the M1 and browser both?

**Comment by adityakailash0399** [comment]
Hey @gkjohnson , Apologies! I got the versions now, I have been using _three-gpu-pathtracer@0.0.11_ and three-mesh-bvh@^0.5.21 .

**Comment by gkjohnson** [comment]
Those versions are many revisions behind and almost a year old... I have already told you to make sure your versions are up to date before testing again. Why ask for help if you just ignore everything I say?

Please do not waste my time again.
