### ISSUE TITLE
All demos crashing on OSX 14.0

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/three-gpu-pathtracer#463]
Related to https://github.com/gkjohnson/three-gpu-pathtracer/pull/457#issuecomment-1763429214

The basic and beauty renders demos work - but the primitives demo does not.

**Comment by robertoranon** [comment]
hi, I pulled the latest changes, and, to be sure, tried on a just restarted machine (2021 Macbook M1 Pro with M1 Max, 32 Gb, 24 cores GPU). I am using the latest OS (Sonoma 14.0), Safari 17.0, Chrome Version 118.0.5993.70.

On Chrome, if I load index.html, it hangs for a while, and then crashes, strangely leaving the standard three.js rendering "on". But the path-tracer shaders fail to compile, the webgl context is lost, the browser hangs and is irresponsive. 

On Safari, I get no errors, but a grey-black grid (see screenshot), except when I rotate the model, where I get standard three.js rendering.

<img width="1129" alt="Screenshot 2023-10-17 at 09 44 31" src="https://github.com/gkjohnson/three-gpu-pathtracer/assets/6480367/4048cf3b-6408-4c32-abfa-dea47a55c632">

As I said in another issue, disabling MIS makes it work on both browsers. Examples that do not use MIS (e.g. aoRender.html) work without modification.

**Comment by gkjohnson** [comment]
I'm on OSX 13.5 so let me upgrade and see what happens 😓

**Comment by robertoranon** [comment]
no pressure :)  btw, great work!

**Comment by robertoranon** [comment]
wow, I don't have that. Safari fails quite gracefully, only Chrome is
kinda frozen (the whole browser, not just the tab). Anyway, maybe it's
possible to check for macos and disable MIS as a temporary workaround? I
am also trying to make it work on iOS, and, besides disabling MIS, I had
some success by substituting the env maps lookups to a fixed color (i.e.
a white dome), I think it's related with the fact that iOS devices,
despite nominally supporting Float32 textures in WebGL, actually behave
nicely only with Float16 ...

On October 17, 2023, "dependabot[bot]" ***@***.***> wrote:
> Yeah I just upgraded and the crash is worse than ever, now, and hangs
> the browser and stalls the OS...
>
> > disabling MIS makes it work on both browsers
> >
>
> In terms of disabling MIS - as I mention in #456
> <https://github.com/gkjohnson/three-gpu-pathtracer/issues/456> this
> really just removes a large swath of code from the shader. It
> unfortunately doesn't tell us a lot about what the issue might be.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/gkjohnson/three-gpu-
pathtracer/issues/463#issuecomment-1766021689>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABROD32DEXABYMSK3Y5XVSTX7ZFCDAVCNFSM6AAAAAA6DEEZOOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONRWGAZDCNRYHE>.
You are receiving this because you commented.Message ID:
***@***.***>

**Comment by gkjohnson** [comment]
Looks like this is possibly an OSX compiler issue:

https://twitter.com/gfxprogrammer/status/1715963911416258769

> Anyway, maybe it's possible to check for macos and disable MIS as a temporary workaround?

Disabling MIS will only really work with a really simple env map so the functionality isn't really equivalent. If users are set up to use a simple map then they should disable MIS. Other than that I'd prefer to see what happens with this on the browser / OS side. 

> I think it's related with the fact that iOS devices, despite nominally supporting Float32 textures in WebGL, actually behave nicely only with Float16 ...

Do you know any more about this or have any references? Have you tried substituting the float32 textures for float16 to see if it fixes other issues?

**Comment by robertoranon** [comment]
Hi, sorry for the delay, I don't have references, but I've seen it reported multiple times. iOS devices do not handle float32 textures correctly in webgl. The problem with substituting with a float16 is that you read the texture back from gpu after e.g. blurring it, and the read operation fills a buffer of float32, so I guess I have to change a bit of code to make it work with float16, e.g. in BlurredEnvMapGenerator:


`// read the data back
		const buffer = new Float32Array( width * height * 4 );
		renderer.readRenderTargetPixels( renderTarget, 0, 0, width, height, buffer );

		const result = new DataTexture( buffer, width, height, RGBAFormat, FloatType );`

btw, why are you loading the texture back from gpu memory? why not directly use a render target texture?

**Comment by gkjohnson** [comment]
> why are you loading the texture back from gpu memory? why not directly use a render target texture?

The distribution of intensity across pixels is calculated on the pixels on the CPU so we know which pixels will to sample from with a higher frequency since brighter pixels will have a higher contribution to the final image.

> The problem with substituting with a float16 is that you read the texture back from gpu after e.g. blurring it, and the read operation fills a buffer of float32, so I guess I have to change a bit of code to make it work with float16, e.g. in BlurredEnvMapGenerator:

There's no need to use a BlurredEnvMapGenerator. If you load an HDR map you can use it directly then everything should still work - you could even copy any loaded float32 buffers to float16 for use with the pathtracer. Finding at which stage a failure occurs. From your first comment it's not clear what kind of problems you're seeing.

**Comment by robertoranon** [comment]
I'll open a specific issue on iOS and describe the problem

**Comment by gkjohnson** [comment]
Fixed in #483
