### ISSUE TITLE
Black triangles on path traced renders

### ISSUE THREAD

**Issue by hybridherbst** [gkjohnson/three-gpu-pathtracer#464]
**Describe the bug**

Getting black triangles on many parts of most models on M2 Mac (with MIS turned off to work around #450 and #463)

**Expected behavior**

Clean(er) renders

**Screenshots and Repro Model**

Default Rover model:
https://github.com/gkjohnson/three-gpu-pathtracer/assets/2693840/b9c912f6-2c47-49d1-8219-7c884eae597e

https://github.com/gkjohnson/three-gpu-pathtracer/assets/2693840/7d4d1056-5722-4128-9b08-a37cfc3d8f91

**Platform:**

 - Device: [Desktop]
 - OS: [MacOS]
 - GPU: [M2]
 - Browser: [Chrome, Safari]
 - Three.js version: [r154]
 - Library version: [v0.0.16]

**Comment by gkjohnson** [comment]
Hey! Do you have any screenshots of the issue?

I'm not super inclined to dig too deeply into this until there's some kind of an update to OSX 14.0 (https://github.com/gkjohnson/three-gpu-pathtracer/issues/463#issuecomment-1774055422) - assuming that's your version - since all this worked in 13.x before upgrading.

If it looks like it won't be addressed then we'll have to figure out what a good path forward is.

**Comment by hybridherbst** [comment]
I had a video attached but somehow GitHub decided to turn it into a download link instead – can you see it now in the original post?

**Comment by robertoranon** [comment]
I had the same exact problem, and it went away by using the latest code pulled from the repository. I have a M1, tough, not an M2

**Comment by hybridherbst** [comment]
I see. I was on the latest npm version but maybe that's very different already. Will try to test over the weekend if that already makes the difference.

**Comment by gkjohnson** [comment]
Yes #457 has been merged but not published so that may have an effect. It looks like this [has been reported to Apple](https://twitter.com/gfxprogrammer/status/1717776110375866750), though, so lets see if something gets addressed on the system side.

**Comment by hybridherbst** [comment]
Oh, cool to see you got some hold on the Mac issues – I'll check!

**Comment by gkjohnson** [comment]
@hybridherbst I'm going to close this for now. If you can confirm it's still happening we can reopen.

**Comment by hybridherbst** [comment]
Sorry, forgot to update here – it's indeed fixed :)
