### ISSUE TITLE
Add demo showing how to render skinned, morph target meshes

### ISSUE THREAD

**Issue by setpixel** [gkjohnson/three-gpu-pathtracer#50]
Hi! I assume not, because of BVH.

**Comment by gkjohnson** [comment]
Can you elaborate on what you'd be looking for? It's not impossible to support SkinnedMeshes but it hasn't been anything I'd considered adding. For more direct support the [three-mesh-bvh](https://github.com/gkjohnson/three-mesh-bvh) library could be updated to account for vertex skinning / morph targets and a BVH could be generated from that though the build process would be slower. And for any changes to the skeleton or morph targets the BVH could be "refit" (https://github.com/gkjohnson/three-mesh-bvh/issues/296, https://github.com/gkjohnson/three-mesh-bvh/issues/284) to encapsulate the new triangle positions which would be faster but still more difficult to do in real time in complex cases and would result in a less optimal BVH.

If you just want to render a deformed, skinned mesh then the simplest approach would probably be to generate a new static or "baked" geometry that represents the skinned mesh and then generate a BVH from that to render.

Does that answer what you're looking for?

**Comment by gkjohnson** [comment]
**Possible Demo Models**
- https://sketchfab.com/3d-models/astraia-c0f37ac567d34fa8881ed7a79b335c4d
- https://sketchfab.com/3d-models/dancing-crab-uca-mjoebergi-280863886fee409ab3c8168f07caa89f
- https://sketchfab.com/3d-models/pigman-f7597d3af7224f7e890710ac27d4d597
- https://sketchfab.com/3d-models/tyrannosaurus-rex-9d3a3e42c0054c35aa39c3ee07388d16
