### ISSUE TITLE
Perform NaN detection

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/three-gpu-pathtracer#53]
And exclude the sample. Use `isnan()` and `isinf()` -- check for black specs?

See if the 0 (or near 0) roughness is NaN issues or something else.

A lot more NaNs / black pixels seem to appear on mobile.

**Comment by bhouston** [comment]
I get black dots on Chrome on M1.  They start off non-existant and then accumulate.  This happens for extreme values like roughness = 0 or metalness = 1.

<img width="1073" alt="Screen Shot 2022-03-31 at 11 32 49 AM" src="https://user-images.githubusercontent.com/588541/161113634-11b3bbda-ec3f-4435-9f26-9294e028fff6.png">

Here is the precision testing page results:

<img width="1204" alt="Screen Shot 2022-03-31 at 1 19 24 PM" src="https://user-images.githubusercontent.com/588541/161113604-24d927eb-3289-4b76-8e45-49b7007e2cbe.png">

I have some code here I've used in the past for "isnan" and "isinf":
```glsl
const float NAN = sqrt( 0. );
bool isnan( const in float x ) {
  // this appears to be against the specification. another solution was offered here:
  // https://www.shadertoy.com/view/lsjBDy
  return (x) == NAN;
}
bool isinf( const in float x ) {
  return (x) == (x)+1.;
}
```

**Comment by gkjohnson** [comment]
`isnan` and `isinf` are actually already available in WebGL2 🎉 But I'm not sure if they're needed. In #54 I changed how I was performing a 0 division check which seems to have made it more robust on my 2017 Surface Laptop in a more extreme scenario. Seems like a compiler issue?

@bhouston can you give the demo a test again to see how it looks?

**Comment by bhouston** [comment]
Black dots no longer appear on M1 Chrome!  Nice work!

<img width="1656" alt="Screen Shot 2022-04-01 at 2 50 08 PM" src="https://user-images.githubusercontent.com/588541/161324120-c20a5c9e-14fd-423f-b7ac-09805e375b04.png">

**Comment by gkjohnson** [comment]
Woo! Great - thanks for testing!
