### ISSUE TITLE
Ambient Occlusion Demo broken on MacOS Ventura 13.0

### ISSUE THREAD

**Issue by anzorb** [gkjohnson/three-gpu-pathtracer#544]
**Describe the bug**

Black Screen on Chrome and Safari on MacOS Ventura 13.0

```
Program Info Log: Fragment shader is not compiled.


FRAGMENT

ERROR: 0:956: 'rand4' : no matching overloaded function found
ERROR: 0:956: 'xy' :  field selection requires structure, vector, or interface block on left hand side
ERROR: 0:956: 'sampleHemisphere' : no matching overloaded function found
ERROR: 0:956: '=' : dimension mismatch
ERROR: 0:956: '=' : cannot convert from 'const mediump float' to 'highp 3-component vector of float'
```

[https://gkjohnson.github.io/three-gpu-pathtracer/example/bundle/aoRender.html](https://gkjohnson.github.io/three-gpu-pathtracer/example/bundle/aoRender.html)

**Expected behavior**

A working example

**Screenshots and Repro Model**
<img width="1470" alt="Screenshot 2024-02-20 at 6 02 54 PM" src="https://github.com/gkjohnson/three-gpu-pathtracer/assets/1194338/725c6975-405b-4b53-9992-57d5335c644f">

**Platform:**

 - Device: [Desktop]
 - OS: [MacOS]
 - GPU: [M2]
 - Browser: [Chrome 121.0.6167.160 +  Safari  16.1 + Safari Tech Preview]

**Comment by gkjohnson** [comment]
Fixed in [c8a2e07](https://github.com/gkjohnson/three-gpu-pathtracer/commit/c8a2e076db7378e225e3e6b81c8c777f7471a04b). Thanks!
