### ISSUE TITLE
Remove threeCompatibilityTransforms

### ISSUE THREAD

**Issue by mrdoob** [gkjohnson/three-gpu-pathtracer#549]
I think these can be removed now?

https://github.com/gkjohnson/three-gpu-pathtracer/blob/0b9ffc9f8deb1d3bcbb58acbf6e5b75c0a13f491/README.md?plain=1#L808-L816

https://github.com/gkjohnson/three-gpu-pathtracer/blob/0b9ffc9f8deb1d3bcbb58acbf6e5b75c0a13f491/src/uniforms/MaterialsTexture.js#L120-L160

**Comment by gkjohnson** [comment]
Do you recall which version of three.js this was fixed in?

**Comment by mrdoob** [comment]
It was r151. https://github.com/mrdoob/three.js/pull/25721#issuecomment-1487170206
