### ISSUE TITLE
Mesh standard Material alpha map not working 

### ISSUE THREAD

**Issue by nightfury07x** [gkjohnson/three-gpu-pathtracer#551]
I have some mesh's with MeshStandardMaterial is applied with alpha map with 

   alpha.wrapS = THREE.RepeatWrapping;
   alpha.wrapT = THREE.RepeatWrapping;
   
   and some repeating  
   Material.alphaMap?.repeat.set(1 / scale, 1 / scale);

alpha map is used to make transparency of the windows of a building but when I try to render it using path-tracer 
I can see the alpha map is not correctly applied to the mesh while rendering (with correct scale)

**Expected behavior**

It should be correctly map with the mesh to show window transparency when rendering 

image before render with correct alpha map placement 
![309722080-ddc2c145-05f7-4715-82b3-9f1b6e7823f5](https://github.com/gkjohnson/three-gpu-pathtracer/assets/37612805/e3fea9cd-e3a8-4157-b6ec-e5d9e95feebe)

image with rendering with wrong alpha map placement
![309722381-593ad7d8-e135-481d-810f-bb8df4af94c8](https://github.com/gkjohnson/three-gpu-pathtracer/assets/37612805/80205481-1c53-4a72-830d-26b81bd14ec7)

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - GPU: [NVidia ]
 - Browser: [Chrome]
 - Browser Version: Version 122.0.6261.95 (Official Build) (64-bit)
 - Three.js version: "three": "^0.161.0",
 - Library version: three-gpu-pathtracer": "^0.0.17

**Comment by gkjohnson** [comment]
Why have you deleted the issue template for reporting a bug? It specifically states to include an example or model to reproduce the issue.

**Comment by nightfury07x** [comment]
> Why have you deleted the issue template for reporting a bug? It specifically states to include an example or model to reproduce the issue.

sorry 
I have updated it now

**Comment by gkjohnson** [comment]
From the template:

> **Screenshots and Repro Model**
>
> Add screenshots and a gltf model to help explain your problem (drag and drop).

Please include all information
