### ISSUE TITLE
Other material orbs

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/three-gpu-pathtracer#56]
https://casual-effects.com/data/

**Comment by AntonPalmqvist** [comment]
The "Standard Shader Ball" scene from ASWF is available here with a CC BY 4.0 license: https://github.com/usd-wg/assets/tree/main/full_assets/StandardShaderBall

**Comment by gkjohnson** [comment]
Thanks - I converted it to glTF with textures and materials here:

https://github.com/gkjohnson/3d-demo-data/tree/main/models/usd-shader-ball

It looks like Blender / glTF doesn't support exporting the area lights so we'll have to recreate those but it will be nice to have a consistent scene for comparisons.

**Comment by gkjohnson** [comment]
I see that the left side area light (15 x 15 m) is set to output 6327.84 W power and the four top lights are set to 11185.5 W power.

cc @donmccurdy do you know the Watt -> Candela conversion for area lights that should be used? I couldn't find one after searching online for a bit.

**Comment by donmccurdy** [comment]
Going from W to lm/sr/m^2, it'd be similar to what you see in Blender:

https://github.com/will-ca/glTF-Blender-IO/blob/af9e7f06508a95425b05e485fa83681b268bbdfc/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_lights.py#L92-L97

Note that even with the correct lighting unit conversion, you will not see the same results without changes to exposure. Unity [glTFast physical lighting guide](https://docs.unity3d.com/Packages/com.unity.cloud.gltfast@5.2/manual/LightUnits.html) goes into some detail on this, but I'm not sure what the three.js equivalent of Blender's default exposure would be. Without that, matching lighting across tools is difficult.

**Comment by gkjohnson** [comment]
Thanks guys! I've updated the database scene to use the latest model and the following lighting conversions:

```js
const area = light.width * light.height;
const lumens = PBR_WATTS_TO_LUMENS * watts;
light.intensity = lumens / ( area * 4 * Math.PI );
```

Link to the demo page is [here](https://gkjohnson.github.io/three-gpu-pathtracer/example/bundle/materialDatabase.html). I'm not a Blender guru by any stretch so I had some issues with the model - specifically some textures seem to be lost in the conversion (specifically the Sub-Surface Bars) so I've hand adjusted the colors in those cases. It also looks like orb surface was tessellated and smoothed for the Blender renders, which would be nice to have in the GLTF representation but I may have to revisit that once I know Blender a bit better.

> you will not see the same results without changes to exposure.

Thanks for the note. I've just hand tuned the exposure, for now, until there's a more reliable way to do this or I have more time to look into it.

**Comment by AntonPalmqvist** [comment]
Great to see the new shader ball in there! 🤩 

To import with subdivision surfaces, check the **Subdivision** box under **Geometry** in the USD import dialog:
<img width="243" alt="Screenshot 2024-07-20 at 10 33 30" src="https://github.com/user-attachments/assets/9635324f-75b3-4a2a-87e0-38a37d413850">

To fix the missing SSS bar texture you need to re-assign the texture here:
<img width="1216" alt="Screenshot 2024-07-20 at 10 37 59" src="https://github.com/user-attachments/assets/771a0ec5-2eb6-4043-ad55-ad5b2a027d74">

Before you export the .glb, make sure to Apply Transforms on the meshes, or just check this box in the glb export dialog:
<img width="249" alt="Screenshot 2024-07-20 at 10 49 36" src="https://github.com/user-attachments/assets/776b05be-25d2-49ba-8a9d-11a2a36bc0b8">

If you haven't already, I'd recommend you update to Blender 4.2 that just got released, as there's a bunch of USD updates in there!

Hope this helps!

**Comment by gkjohnson** [comment]
Thanks! So much nicer:

<img width="322" alt="image" src="https://github.com/user-attachments/assets/937a1b1d-6c86-47a1-ac0b-237a69fbb445">

<img width="323" alt="image" src="https://github.com/user-attachments/assets/125620e2-bd92-4867-8ece-dad6404bdea0">

One other question while it's on my mind - when loading the scene I'm multiplying the camera FoV 2x because otherwise it's pulled in really close. It's the same in Blender. Is this another import quirk? Here's the camera view from Blender.

<img width="400" alt="image" src="https://github.com/user-attachments/assets/e69c8dd0-c439-445c-95a8-b89a9f72d863">

**Comment by AntonPalmqvist** [comment]
It seems that the camera was made for a square format render output, but since the USD import doesn't set any of the render settings you need to set the Output Resolution to a square format resolution in Scene settings:

<img width="2049" alt="Screenshot 2024-07-20 at 17 02 44" src="https://github.com/user-attachments/assets/c9a68425-bbb8-4e77-99b9-cdb27127eeb6">
