### ISSUE TITLE
Use blue noise for randomness

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/three-gpu-pathtracer#59]
https://developer.nvidia.com/blog/rendering-in-real-time-with-spatiotemporal-blue-noise-textures-part-1/

**Comment by gkjohnson** [comment]
https://alain.xyz/blog/ray-tracing-filtering

**Comment by gkjohnson** [comment]
https://hal.archives-ouvertes.fr/hal-02158423/file/blueNoiseTemporal2019_slides.pdf

**Comment by gkjohnson** [comment]
https://blog.demofox.org/2020/05/16/using-blue-noise-for-raytraced-soft-shadows/

**Comment by gkjohnson** [comment]
https://alain.xyz/blog/ray-tracing-filtering

**Comment by gkjohnson** [comment]
Some recommended resources from [Twitter](https://twitter.com/garrettkjohnson/status/1603023737577668609).

**Comment by gkjohnson** [comment]
**Notes**
- Padding: simple calculations for higher dimensions of sampling instead of compute proper low discrepancy values for all dimensions.
- Padding can be computed using basic randomness or randomized sobol sequence.
- Best to use randomized sobol sequence since it's not always clear which dimensions need low discrepency.

**Comment by gkjohnson** [comment]
Stratification and improved sampling techniques are now added but adding a blue-noise error distribution to the initial images is more complicated (See Heitz' 2019 paper referenced by Alan above) and I think out of scope at the moment.

**Comment by tigrazone** [comment]
one more interesting https://perso.liris.cnrs.fr/david.coeurjolly/publications/perrier18eg.html
