### ISSUE TITLE
Index in README

### ISSUE THREAD

**Issue by JaimeTorrealba** [gkjohnson/three-gpu-pathtracer#638]
Since the README is long it might be useful to have a simple index, so every time someone needs a component, for example, doesn't need to scroll

As I'm new here, I come with something like:

![image](https://github.com/gkjohnson/three-gpu-pathtracer/assets/63722373/41871e89-03b3-48c4-b89d-ecfbb0338596)

A simple table with the proper links, Now if you like we can add titles or other sections. This could be handy for the other siblings projects (like bvh/csg)

If you like, I will open the PR here (later in other pkg)

**Comment by gkjohnson** [comment]
Thanks for the recommendation. There's a built-in table of contents in Github that lets you search through the contents, as well:

<img width="434" alt="image" src="https://github.com/gkjohnson/three-gpu-pathtracer/assets/734200/1a840010-bf5a-4f9d-aace-165beecfbd15">

It looks like this is what you're looking for? In general I'd prefer to avoid hand-maintaining a list of headers that people may want to visit if possible.

**Comment by JaimeTorrealba** [comment]
Indeed thanks
