### ISSUE TITLE
Line2 object render error, just show as a plane

### ISSUE THREAD

**Issue by Milesssssss** [gkjohnson/three-gpu-pathtracer#643]
<img width="493" alt="image" src="https://github.com/gkjohnson/three-gpu-pathtracer/assets/6835957/39f21965-7b0a-47cd-bb89-0c92271c064d">

Code demo
``` 
const l = new Bezier({
      x: -3, y: 0, z: 0
    }, { x: 2, y: 0, z: 0 }, { x: 3, y: 0, z: 0 })
    const lineGeometry = new LineGeometry()
    const ps = l.getLUT(10).flatMap(r => {
      return [r.x, r.y, r.z]
    })
    lineGeometry.setPositions(ps)
    const test = new Line2(lineGeometry, new LineMaterial({
      color: 0xff0000,
      linewidth: 0.005,
      dashed: false,
    }))
    test.computeLineDistances()
```

 - Device: [Desktop]
 - OS: [MacOS]
 - GPU: [M3]
 - Browser: [Chrome]
 - Browser Version: [124.0.6367.119]
 - Three.js version: [r164]
 - Library version: [v0.0.22]

**Comment by gkjohnson** [comment]
The path tracer only supports Mesh geometry and does not support instancing or custom shaders - both of which Line2 uses. If you'd like to render the line on top of the path traced model you'll have to render it in a separate pass or convert it to a 3d mesh like a tube before path tracing.

**Comment by Milesssssss** [comment]
Get it.
