### ISSUE TITLE
vue+webpack use three-gpu-pathtracer

### ISSUE THREAD

**Issue by LiuXIn011** [gkjohnson/three-gpu-pathtracer#667]
![QQ浏览器截图20240802115359](https://github.com/user-attachments/assets/e164a4d3-3a5a-4c3d-a0aa-f3f5edfa2599)
use loader
![image](https://github.com/user-attachments/assets/f02bdb63-c840-4393-ae25-1b073d2411a1)

**Comment by gkjohnson** [comment]
This project only uses valid javascript syntax. You should report your issue to Vue.
