### ISSUE TITLE
setSceneAsync take time to fire the first event

### ISSUE THREAD

**Issue by Wizer21** [gkjohnson/three-gpu-pathtracer#669]
Hello !
I'm posting here because I have a issue while using the setSceneAsync function.
For a model that take 35seconds to load, the first event is fire after 16s.

- The model has around 4M vertices seperated in 22 meshes.
- I tried with a single texture on the model, the timers are the same
- The worker is the GenerateMeshBVHWorker
- I'm in a vite/vue config, so I added this line in vite.config.ts
optimizeDeps: {
  exclude: ['three-mesh-bvh/src/workers/GenerateMeshBVHWorker.js', 'three-mesh-bvh/src/workers/ParallelMeshBVHWorker.js'],
},

Thanks for the help ! :)

The model:
![cover](https://github.com/user-attachments/assets/3729eae3-afd2-453c-bef5-3267fb0adb5d)
How I populate the scene
<img width="419" alt="populate+" src="https://github.com/user-attachments/assets/7efcb2d8-64d9-4cef-95d7-4ae11a2af42c">
The setSceneAsync ( the logs are comented )
![Sans titre](https://github.com/user-attachments/assets/3189aa0c-694e-419d-84f3-f3ef91bc3460)
Timers logs:
![time](https://github.com/user-attachments/assets/48b86095-fcc0-4513-8e7b-c545e0ab8f2c)

ParallelMeshBVHWorker not supported
<img width="269" alt="warning" src="https://github.com/user-attachments/assets/cd30dd01-75c3-49db-8368-1e8ee641ae87">

 - Device: Desktop
 - OS: Windows 11
 - Browser: same issue on Chrome and Edge
 - Three.js version: 0.166
 - three-gpu-pathtracer version: 0.0.23
 - three-mesh-bvh version: 0.7.6

**Comment by gkjohnson** [comment]
Have you run a performance profile to see where the time is going? Without a live example it's impossible to say exactly what's happening.

**Comment by Wizer21** [comment]
I'm sorry I know if I can put the model on something like dribble.
So i've made a public repo, with a smaller model ( the original one was too big for git hub )
https://github.com/Wizer21/pathtracer_test

Making the test version above I've discover that the setSceneAsync only take 4s to start instead of 16s.
But I'm still trying to figure out why.

And i've found that on the initial website, if I remove the .clone() on the meshes that I provide to the pathtracer, the set scene is twice longer
![Sans titre](https://github.com/user-attachments/assets/aebbd253-784e-4b32-9a99-b521853def35)

**Comment by gkjohnson** [comment]
I've loaded the model and it works fine. What exactly is the issue? The bounding volume hierarchy takes time to generate which is what the "onProgress" is for so you can display progress to the user or whatever you need. If you use the parallel bvh worker you'll see that the generation can improve by 3 or 4 times. There are other methods that could be used to improve bvh generation performance but they are not implemented here.

**Comment by Wizer21** [comment]
The extra time was due to the fact that I was recreating a new scene and cloning the elements inside.
A scene that used to take 42 seconds to calculate now only takes 20 seconds if you keep the same instance.
