### ISSUE TITLE
UVUnwrapper.js contains obsolete `addAttribute()` function

### ISSUE THREAD

**Issue by GitHubDragonFly** [gkjohnson/three-gpu-pathtracer#677]
**Describe the bug**

It appears that three.js revisions higher than r140 would throw an error while r139 and r140 log a warning about the `addAttribute` function being renamed to `setAttribute`.

**Expected behavior**

Using the `setAttribute()` function should eliminate both warnings and errors.

**Screenshots and Repro Model**

This particular unwrapper I tested as an independent import just to see if it can function as such, without using the three-gpu-pathtracer library (so not sure where exactly in the library this unwrapper might be used).

**Platform:**

 - Device: [Laptop]
 - OS: [Windows]
 - GPU: [integrated NVidia GeForce]
 - Browser: [Firefox]
 - Browser Version: [132.0 (64-bit)]
 - Three.js version: [r140+]
 - Library version: [v0.0.23]

**Comment by gkjohnson** [comment]
Thanks - the UVUnwrapper class isn't used and hasn't really been developed and isn't exposed. It was originally added with the plans to (eventually) build it out to support uv unwrapping but that never happened. #670 adds support for some more complete utilities for uv unwrapping and ao mapping but there are still some more changes needed, I think.

The [xatlas-three](https://github.com/repalash/xatlas-three) is also a very good uv unwrapper implementation.

**Comment by GitHubDragonFly** [comment]
Just as an FYI, there is a [topic](https://discourse.threejs.org/t/uv-unwrapping-experimental-for-ply-and-stl-models/73641) in the forum which shows how I experimented with a modified version from your repository and with xatlas-three after you suggested it.
