### ISSUE TITLE
Demo: Add more environment map options

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/three-gpu-pathtracer#88]
With more contrast / fewer ambient light sources

https://polyhaven.com/hdris

**Comment by DennisSmolek** [comment]
This could be a good usecase to do a R3F demo because the DREI library has the same Envmaps built in: https://github.com/pmndrs/drei#environment

**Comment by mikelyndon** [comment]
It would also be great to remove the current assets from the repo and use polyhaven's api instead to improve download times when cloning the repo. :)
