### ISSUE TITLE
Add support for iridescence

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/three-gpu-pathtracer#96]

**Comment by bhouston** [comment]
Iridescence is a very important property in many situations - such as oil slicks, or on leather furniture as well as some exotic car paints or ceramics.

We should follow the glTF iridescence model specified here:

https://github.com/KhronosGroup/glTF/blob/a9cd1cb657587b590b6f95c8654038a4e9d66596/extensions/2.0/Khronos/KHR_materials_iridescence/README.md

It has these properties:

|                                 | Type                                                                                                 | Description                                                       | Required            |
| ------------------------------- | ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------| ------------------- |
| **iridescenceFactor**           | `number`                                                                                             | The iridescence intensity factor.                                 | No, default:`0.0`   |
| **iridescenceTexture**          | [`textureInfo`](https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#reference-textureinfo) | The iridescence intensity texture.                                | No                  |
| **iridescenceIor**              | `number`                                                                                             | The index of refraction of the dielectric thin-film layer.        | No, default:`1.3`   |
| **iridescenceThicknessMinimum** | `number`                                                                                             | The minimum thickness of the thin-film layer given in nanometers. | No, default:`100.0` |
| **iridescenceThicknessMaximum** | `number`                                                                                             | The maximum thickness of the thin-film layer given in nanometers. | No, default:`400.0` |
| **iridescenceThicknessTexture** | [`textureInfo`](https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#reference-textureinfo) | The thickness texture of the thin-film layer.                     | No                  |

**Comment by bhouston** [comment]
I am pleased to be able to put a bounty of $500 USD on an accepted PR that implements the official glTF iridescence extension in this path tracer.

**Comment by richardassar** [comment]
Have gathered a few resources and started taking a look at this. :microscope:

**Comment by richardassar** [comment]
Here are the results after a quick first pass at this, just showing the dielectric component for now. 

I need to cross-reference with the other glTF extensions to ensure everything is integrated correctly with the existing material code, but here's how it looks at present.

![Screenshot 2022-06-21 at 14-40-30 Material Orb Path Tracing](https://user-images.githubusercontent.com/868396/174819149-d3251a49-21b1-4f5f-995c-81670a5a0342.png)

![Screenshot 2022-06-21 at 14-42-37 Material Orb Path Tracing](https://user-images.githubusercontent.com/868396/174819204-87e84c82-50cf-41b4-86d6-75e4fd9ee0e9.png)

![Screenshot 2022-06-21 at 14-16-50 Material Orb Path Tracing](https://user-images.githubusercontent.com/868396/174819392-3e16cabf-a02b-4bee-afdc-64fee40c44a2.png)

![Screenshot 2022-06-21 at 14-44-52 Material Orb Path Tracing](https://user-images.githubusercontent.com/868396/174819347-c313c071-f666-49ca-9b35-4458e6ddaf5a.png)

**Comment by richardassar** [comment]
After some improvements and fixes:

![Screenshot 2022-06-22 at 05-51-48 Material Orb Path Tracing](https://user-images.githubusercontent.com/868396/174946369-ac89dcf0-267e-4444-9658-c81216514f5a.png)

![Screenshot 2022-06-22 at 04-25-51 Material Orb Path Tracing](https://user-images.githubusercontent.com/868396/174946384-c8c16abe-cd7e-490a-8e99-759a9b4920be.png)

![Screenshot 2022-06-22 at 05-41-09 Material Orb Path Tracing](https://user-images.githubusercontent.com/868396/174946387-a188bb59-8c8d-4df0-b797-d7f2c89ff365.png)

There are still a few things to figure out but it's getting there.

**Comment by richardassar** [comment]
Thanks, and no problem at all, no rush for a review - I still have to resolve the issue of the lights failing to render in non-MIS mode.

**Comment by bhouston** [comment]
This is beautiful!

**Comment by richardassar** [comment]
Thanks @bhouston :)

**Comment by richardassar** [comment]
Changes are in https://github.com/gkjohnson/three-gpu-pathtracer/pull/206, ready for review.
